### PR TITLE
Sass Compile Errors

### PR DESCRIPTION
**Pull request by kristremblay**
Applied fixes outlined in https://github.com/wet-boew/wet-boew/issues/7035#issuecomment-165894964.

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Before merging this, we should find out why Travis's and almost everyone else's don't fail on this

**Comment by andre-gh** [comment]
Something lies in

> This may be because I am compiling with vanilla sass and it's picky in that situation.

I am not sure what that implies, but that sounds like the answer.

**Comment by LaurentGoderre** [comment]
Ok, I reproduced by installing the ruby version of sass

**Comment by LaurentGoderre** [comment]
Here is the bug report: https://github.com/sass/libsass/issues/871

**Comment by andre-gh** [comment]
@LaurentGoderre Looks like our issue then, good to merge?

**Pull request merged**
