### PR TITLE
Update bower.json

### PR DESCRIPTION
**Pull request by pathiyani**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@lucas-hay should we block this user? He seems to be sending random PRs

**Comment by RobJohnston** [comment]
This one and the other two or three from the last week are clearly bots.  Can bots be reported to GitHub?

**Comment by rlambert27** [comment]
Bots? At least a bot coudl spell better instead of butter. :p

**Comment by lucas-hay** [comment]
@LaurenGoderre yes. Go ahead and block. If you don't have the proper permissions I can do it later.

**Comment by nschonni** [comment]
Weird I actually already blocked them, but I guess the block might need to be someone with Owner. I didn't report them though

**Comment by LaurentGoderre** [comment]
@lucas-hay I can't

**Comment by lucas-hay** [comment]
@LaurentGoderre I just blocked him/her/it. :-)

**Pull request closed without merging**
