### PR TITLE
Build: Include jQuery for offline/internal sites or application

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by masterbee** [comment]
@LaurentGoderre this is a bit of a reverse direction since we decided in the beginning versions to stay with parameterless. While I am not opposed to it, is there a reason why it should be folded back in to the mix again.

**Comment by LaurentGoderre** [comment]
Parameterless? We have intranet application that do not have intranet connectivity so it would be easier if the WET package included the right versions of jQuery instead of implementors having to figure out the version number and downloading it manually.

**Comment by LaurentGoderre** [comment]
Btw, this does not switch the URL, it just includes the files in case you need them for site or apps that can't access the CDN

**Comment by masterbee** [comment]
@LaurentGoderre - ok I can see the benefit there. The issue was more that adding pre-canned jQuery can sometimes create problems in term of applications and CMS since jQuery and developers would have to do that research regardless.

**Pull request merged**
