### PR TITLE
Improved sass-lint

### LINKED ISSUE #7525: Set `no-misspelled-properties` to error when sass-lint fixes nested property
sasstools/sass-lint#352

### PR DESCRIPTION
**Pull request by LaurentGoderre**
Restored property spelling checking and fixed indentation handling. Fixes #7525

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@nschonni do yopu know why tests are not run on the default (short) build?

**Comment by LaurentGoderre** [comment]
UUUGH! Now sasslint chokes on -webkit attributes it seems....

**Comment by nschonni** [comment]
Just the specific ones I guess https://github.com/sasstools/sass-lint/issues/693

**Comment by nschonni** [comment]
Although I would have thought that should be handeld by Autoprefixer rather than a manual vendor prefix in the Sass

**Comment by LaurentGoderre** [comment]
@nschonni autoprefixer is for the ones that are in the spec but still have the vendor ones for older version. This one is not in spec so there is no non-vendor option. Not sure autoprefixer can support that

**Pull request merged**
