### PR TITLE
Plugin Menu: replaces Javascript setTimeout to a css delay

### PR DESCRIPTION
**Pull request by stevenbriscoeca**
Edit: by doing a rebase I needed to delete my master branch so it doesn't recreate a merge (sorry about that)

So this is my first commit to get my feet WET.

I made the menu have a delay without JavaScript by only using css delays. I also made it that the submenu styles are there by default and not just when you add the class .sm.open.

Now I am fully aware that menus are complex. This pullrequest is just to see you guys thoughts on the modification. If you like it, great! If you don't, no worries, I will work on something else WET related or update the pull request if you like the direction.

Let me know your thoughts.

Stephen

https://github.com/wet-boew/wet-boew/pull/6792

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Can i be mean and ask to to squash those commit into one (using another rebase). It also looks like there's a build error

**Comment by LaurentGoderre** [comment]
The build error is because css properties need to be listed alphabetically.

**Comment by stephenbe** [comment]
@LaurentGoderre No problem at all, I will get everything into one commit and make the scss linting pass! I will notify you when everything is done and ready to go.

@pjackson28 I will test IE8 IE9 and get back to you with a definite answer very soon!

**Comment by stephenbe** [comment]
@pjackson28 

IE8 : 
ie8


IE9 : 
ie9

**Comment by pjackson28** [comment]
Oh, so the big difference is there is no longer a 0.5ms delay under IE8 and IE9. Is there some way to add this that back that is just targetted at IE8 and IE9? I'm just mindful of the delays being there to address a usability issue.

@thomasgohard What are your thoughts on this?

**Comment by stephenbe** [comment]
hmm didn't seem to work, back to the drawing board, I will end up getting this.

**Comment by LaurentGoderre** [comment]
Ok try this

````
git fetch upstream 
git rebase upstream/master
git push -f origin master 
```

**Comment by stephenbe** [comment]
okay that<s the result, at least the merge commit is gone, I guess it's just retrying to squash the commits again with git rebase -i HEAD~5

Thank you!

**Comment by LaurentGoderre** [comment]
Nice!! Rebasing is a tricky thing to learn but you will really like its power

**Comment by stephenbe** [comment]
I FINALLY DID IT! YES!!!! THANK YOU!

I literally just danced haha.

Now I just need to fix the travis error and we are good to go

Thank you so much for your patience

**Comment by LaurentGoderre** [comment]
The force is strong in you!

**Comment by stephenbe** [comment]
haha thank you I could not have done it without your help!

**Comment by stephenbe** [comment]
I'll finish this up later tonight and QA it make sure nothing has been lost.

**Comment by stephenbe** [comment]
@LaurentGoderre The travis build is now passing. Thus, everything is ready to go! I'll probably create a branch and work on other parts of wet until we know what is going to happen with this PR!

**Comment by LaurentGoderre** [comment]
:+1:

**Comment by stephenbe** [comment]
@LaurentGoderre I think we should close this issue because I need my master to be up to date for my branches to work, but it wont work if I have a PR open with my master...

I'm really sorry about this, all the problems are the fact that I didn't do a branch from the get go

I apologize for this.

**Comment by LaurentGoderre** [comment]
No problem, you can reopen with a new branch

**Pull request closed without merging**
