### PR TITLE
Data-json - Add support for content importation

### PR DESCRIPTION
**Pull request by duboisp**
Note: Depend on #9630

### CODE REVIEW

**Comment by duboisp** [comment]
Added the commit of the dependent PR, so once 9630 is merged this PR would only contains 1 commit.

**Comment by duboisp** [comment]
Pre-approved once location testing and review completed

**Review by polmih — DISMISSED** [review]
Code review done, and tested locally!

**Review by polmih — DISMISSED** [review]

**Review by polmih — DISMISSED** [review]

**Comment by duboisp** [comment]
I rebased the PR

**Review by polmih — APPROVED** [review]
Approved after the rebase

**Pull request merged**
