### PR TITLE
Data-AJAX: Added ability to filter by URL hash or selector

### LINKED ISSUE #6563: Data Ajax: pulling in content by id not working
In WET version 4.0.3 and prior, there was a function available for the data ajax script to directly pull content from a page by ID, class or tag.  For example the ajax call would be something like 
="ajax/data-ajax-extra-2-en.html #ajax-content"
that would pull content wrapped with the id of "ajax-content".  You can further customize it by pulling in by class and/or certain tags within that content.
As of version 4.0.4, that function has disappeared due to a change in the ajax-fetch and data-ajax scripts in the wet-boew.js script.   Is it possible to get this function back for a future version of WET4?  Or is there a new way to pull in content based on id/class/tag??

### PR DESCRIPTION
**Pull request by pjackson28**
Fixes #6563

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Before merging, we need to add a unit test for this scenario. I can take care of that if you want

**Comment by pjackson28** [comment]
Yes please.

**Comment by pjackson28** [comment]
@LaurentGoderre Do you have an estimate of when the unit testing will be ready? If it won't be ready before v4.0.12 then we should merge this PR in as is and bring in the unit testing later (as soon afterwards as possible) since there is a potential for the related issue to be a blocker for some migration.

**Comment by LaurentGoderre** [comment]
While implementing the test, I found something unclear about this....If no filtered content is found, the plugin should not include all the rest of the content, it probably should ignore the request.

**Comment by LaurentGoderre** [comment]
@pjackson28 I opened a PR on your branch for the test.

**Comment by pjackson28** [comment]
It was intentional to return the content but if it is better to return nothing then you can switch it to that. I was just concerned about the URL hash being used for another purpose and inadvertently filtering out all content.

**Comment by pjackson28** [comment]
Note that the same was done for the Lightbox PR.

**Comment by LaurentGoderre** [comment]
I'm closing this one in favor of #6625

**Pull request closed without merging**
