### PR TITLE
helpers: adjust passport pattern in findPotentialPII

### PR DESCRIPTION
**Pull request by polmih**
## What does this pull request (PR) do? / Que fait cette demande « pull » (PR)?
In helpers: 

- adjust passport pattern in findPotentialPII;
- create test cases for findPotentialPII;

### CODE REVIEW

**Comment by duboisp** [comment]
@polmih can you provide all the strings that have been used for testing to find potential PII? Thanks

**Comment by duboisp** [comment]
You can create the test into a "test.js" in the core folder beside the helper file.

You can structure you file like the "src/plugin/feeds/test.js". You will need to describe the test. There is no need to using the other helper there. You can call directly `wb.findPotentialPII()` and assert by using the function

```js
it( "should match canadian nr passport", function() {
  expect( wb.findPotentialPII( "PATTERN" ) ).to.equal( "EXPECTED TRIMMED STRING" );
});
```

**Comment by polmih** [comment]
> You can create the test into a "test.js" in the core folder beside the helper file.
> 
> You can structure you file like the "src/plugin/feeds/test.js". You will need to describe the test. There is no need to using the other helper there. You can call directly `wb.findPotentialPII()` and assert by using the function
> 
> ```js
> it( "should match canadian nr passport", function() {
>   expect( wb.findPotentialPII( "PATTERN" ) ).to.equal( "EXPECTED TRIMMED STRING" );
> });
> ```

Test cases added. Thanks

**Review by duboisp — APPROVED** [review]
Tested locally and work as expected.

Thanks @polmih for adding some unit testing

**Pull request merged**
