### PR TITLE
Added prepare script to allow themes to use WET core via npm

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Review by nschonni — APPROVED** [review]
👍 if you think this will work for the downstream issue. I don't see any harm in it being here. I'll create a separate issue or find the old NPM publishing one

**Comment by duboisp** [comment]
@LaurentGoderre thanks for the contribution.

Just a reminder, as introduced in #8279, that prior to merge a PR that wasn't not being discussed and approved at the technical review meeting the person who merge the PR need to provide a justification within the merge commit of why the PR need to be merged in sooner.

Can you confirm this PR is related to #8253 Bower dependency to NPM, a major change to the build script, in order to fix a few breaking changed that its introduced?

Thank you

**Comment by LaurentGoderre** [comment]
Yep. This is to fix the themes build.

**Pull request merged**
