### PR TITLE
Assemble templates improvements

### PR DESCRIPTION
**Pull request by LaurentGoderre**
<del>TODO: Modify the themes assemble to not double include markup</del>

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Just making a final check but this is ready to merge. Any issuw with it @masterbee @pjackson28 ?

**Comment by pjackson28** [comment]
Could you post a diff of the before and after generated HTML in a gist? These changes should result in no changes to the resulting HTML so it is important that we confirm that.

**Comment by LaurentGoderre** [comment]
Here are the diffs: 

Core: https://gist.github.com/LaurentGoderre/3e566e794971bf25b791?w=0
Base Theme: https://gist.github.com/LaurentGoderre/e59ff438d38d45cc99ba
GC Intranet: https://gist.github.com/LaurentGoderre/edb370f14f537d7f1ffc
GCWU Theme: https://gist.github.com/LaurentGoderre/f8473b6598f4b4263329
OGPL Theme: https://gist.github.com/LaurentGoderre/f5f6725bd6034b3b9134
GCWeb Theme: https://gist.github.com/LaurentGoderre/fdf8c41ce0a4006059e9

There is a markup change in GCWeb but it is non breaking.

**Comment by LaurentGoderre** [comment]
Can we merge?

**Comment by pjackson28** [comment]
The diffs are driving my browser into the ground. What is the markup change you are seeing? Could you please summarize it in this thread?

**Comment by LaurentGoderre** [comment]
For all but the GCWeb theme, the only difference is in whitespace. I could try to generate the diff excluding the unmin folder.

For GCWeb,The h2 is move out of the div and under the section to bring it inline with the other themes. However it existing implementation, it makes 0 difference wheter it is one place or the other.

**Comment by pjackson28** [comment]
Whitespace changes shouldn't be an issue but @masterbee will have to weigh in on the h2 move in GCWeb (his decision to make).

**Comment by LaurentGoderre** [comment]
I can make a version that doesn't have those change in GCWeb and another PR to drop the custom file need to not have the markup change

**Comment by LaurentGoderre** [comment]
@pjackson28 I updated the diff to exclude the unmin folders.

**Pull request merged**
