### PR TITLE
DataTable: Fixed ambiguous page links

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@pjackson28 any issue with this one?

**Comment by pjackson28** [comment]
Why aria-label? Why not update the link text and hide the page with wb-inv? It should be better supported than aria-label.

Don't we already have the translation for page already for all 33 languages?

**Comment by pjackson28** [comment]
Looks like we have main-page. Perhaps that can help with the other languages.

**Comment by LaurentGoderre** [comment]
It's not an issue to use wb-inv but aria-label would be easier to submit upstream. I will switch it anyways

**Comment by LaurentGoderre** [comment]
@pjackson28 shouldn't we be adding href="#" to all those links so that we are not solely relying on the ARIA state?

**Comment by pjackson28** [comment]
If we add anything it should be href="javascript;" rather than href="#". Having just the "#" can result in unexpected behaviour in some cases. For instance if the default is not prevented it would apply focus to the body rather than keeping focus where it is currently.

**Comment by LaurentGoderre** [comment]
Oh you're right, but we should add something, otherwise it is not registered as a link

**Comment by LaurentGoderre** [comment]
Any issue remaining or can I merge?

**Pull request merged**
