### PR TITLE
fixed PR #6703 to make the tabs more accessible

### PR DESCRIPTION
**Pull request by shawnthompson**

### CODE REVIEW

**Comment by shawnthompson** [comment]
@EricDunsworth it passed!
@LaurentGoderre are you ok with the change to the `Rakefile`?

**Comment by EricDunsworth** [comment]
@shawnthompson Awesome :)!

**Comment by LaurentGoderre** [comment]
I already commited the PR from @EricDunsworth to fix this. Can you rebase the initial PR instead?

**Comment by shawnthompson** [comment]
Ok so we got the original PR to rebase and merge with no error so I'm closing this!

GO TEAM WET

cc/ @LaurentGoderre, @EricDunsworth and @rlambert27

**Pull request closed without merging**
