### PR TITLE
JSON fetch and data JSON plugin

### PR DESCRIPTION
**Pull request by duboisp**
Insert content extracted from a JSON file. Data are selected as per JSON Pointer URI Fragment, [RFC6901](https://tools.ietf.org/html/rfc6901)

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
You are using this to display raw JSON on a page?

**Comment by duboisp** [comment]
@LaurentGoderre by "raw JSON" I assume you means a "value in a JSON". If so yes. I have various use case from various department that support this particular feature. For example, take department that need to show the same fees for one particular services on multiple static pages. Right now, in order to avoid legal pursuit of publishing outdated fees, they simply put a link to a page with big list of uncomprehensive schedules of fees. And that is not good for the user experience.

Cheers

:-)

**Comment by LaurentGoderre** [comment]
If that is really the case, why not create a plugin on top of the data-ajax plugin that only deals with the JSON traversal instead of duplicating almost all the code?

**Comment by duboisp** [comment]
That was what I tried at the first instance but ajax-fetch used by data-ajax :
* do not support JSON pointer fragment selection, as per RFC6901
* put the response in a DOM object, as that action it not needed for a JSON file
* do not have a local cache control, like if there is more than one use of the data-json plugin that is about querying the same json file, then it was resulting that ajax-fetch downloaded twice the json file.
* Code become messy and heavier when a plugin needs to do two ajax-fetch, like one to get a template and the second to get the data.

**Pull request merged**
