### PR TITLE
Updated bower dependencies

### LINKED ISSUE #6737: Update dependencies
We are starting to fall behind on the dependencies so should review and update as needed. For instance we are running on jQuery 2.1.1 when the latest is 2.1.3. We are likely behind on a few dependencies so perhaps we could save some time by testing multiple updates in parallel.

### PR DESCRIPTION
**Pull request by LaurentGoderre**
Fixes #6737

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@zachfalsetto we will need to test to make sure this doesn't break anything

**Comment by zachfalsetto** [comment]
Just went through the working examples and I didn't see any issues.

**Comment by LaurentGoderre** [comment]
Ok, we will merge first thing in v4.0.15.

**Comment by hsrudnicki** [comment]
Can this dependable issue be closed as well?

**Pull request merged**
