### PR TITLE
Edit event handler for closing a modal popup, when attribute target _…

### PR DESCRIPTION
**Pull request by ipaksc**
…blank is set

### CODE REVIEW

**Review by duboisp — CHANGES_REQUESTED** [review]
I approve the code change, but it need to include the documentation before to we go forward and merge it.

**Comment by ipaksc** [comment]
@duboisp Hi Pierre: I have updated the documentation. Did you have a chance to review it?

**Comment by GormFrank** [comment]
> 
> 
> @duboisp Hi Pierre: I have updated the documentation. Did you have a chance to review it?

I can't see the documentation in the Files changed

**Comment by ipaksc** [comment]
@GormFrank The pages have been updated

**Review by duboisp — APPROVED** [review]

**Pull request merged**
