### PR TITLE
Form Validation: Added support for a single required checkbox

### LINKED ISSUE #6638: Form validation: required checkbox that is on its own and not in a fieldset asterisk issue
We've come across instances where we require a single checkbox not in a fieldset and it is a required field. It seems that the asterisk bleeds into the checkbox. We've played with the CSS a bit as follows to get the red asterisk to appear before the checkbox but not sure if this can maybe be properly added to WET framework too? Thank you.

'''
div.checkbox.required:before{
        content:"* ";
        color: red;
        margin-left:-.665em
}
'''

### PR DESCRIPTION
**Pull request by LaurentGoderre**
Fixes #6638

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@thomasgohard @pjackson28 any objection to this?

**Comment by thomasgohard** [comment]
Should we also include `input[type="checkbox"]` for when the `checkbox` class isn't applied?

**Comment by LaurentGoderre** [comment]
That has the risk of being to intrusive. Isn't the checkbox class from bootstrap?

**Comment by thomasgohard** [comment]
Yes, the `checkbox` class is from Bootstrap. Bootstrap applies most styling to both `input[type="checkbox"]` and the `checkbox` class. So doing the same here would be consistent.

All the `checkbox` class seems to do differently is to remove the bold treatment on the label element.

**Pull request merged**
