### PR TITLE
Form Validation Update

### PR DESCRIPTION
**Pull request by ghost**
Allows on tab validation (currently need to hit submit before tab validation works).

Also fixes issue discussed in https://github.com/wet-boew/wet-boew/issues/6834 and https://github.com/wet-boew/wet-boew/pull/7913

### CODE REVIEW

**Comment by shawnthompson** [comment]
https://shawnthompson.github.io/kodecount-frmvld-update/unmin/demos/formvalid/formvalid-en.html

**Comment by shawnthompson** [comment]
@neoinsight What do you think about this functionality?

https://shawnthompson.github.io/kodecount-frmvld-update/unmin/demos/formvalid/formvalid-en.html

**Comment by neoinsight** [comment]
@shawnthompson This looks good - nice to have validation before submit rather than all at once. Although am not sure I'm looking at the right thing because if I tab on the current WET demos page, I get validation right away...

**Comment by shawnthompson** [comment]
The current one does format validation only right away (using letter in a phone number) but not required fields

**Comment by neoinsight** [comment]
Ah - that would be great for screen-reader users! They have been way more likely to miss required fields in our testing, and of course have a harder time handling the error. Nice and good fit with steps.

**Review by lucas-hay — APPROVED** [review]
Approveed at PR review meeting.

**Comment by shawnthompson** [comment]
@kodecount @lucas-hay 

I'm using NVDA to test the new form validation required and notice the focus is off once the user tabs out of the required field, the user is notified that it's required but the focus is now on the next focusable element.

Not sure if this is an issue and I'm not sure what to do about it because if we force the focus, we would be holding the cursor hostage in the required field. 

Maybe adding further instructions for non visual users asking them to return to the previous field and fill in the required information???

Just a thought... Can turn this into an issue if we really think it's a problem.

**Pull request merged**
