### PR TITLE
Site: Added the missing v4.0.16 release info to the version index pages

### PR DESCRIPTION
**Pull request by TTVXStarWake**
Updated index-en and index-fr

### CODE REVIEW

**Comment by andre-gh** [comment]
Noticed the versions page was missing the new version

**Comment by MaximMartel** [comment]
@LaurentGoderre does it look good?

**Comment by MaximMartel** [comment]
@andre-gh Thanks for that! I missed that page.

**Comment by LaurentGoderre** [comment]
Could make the commit message more descriptive like

Site: Added the missing v4.0.16 release info to the version index pages

**Comment by MaximMartel** [comment]
@LaurentGoderre  done.

Did git commit --amend -m "Site: Added the missing v4.0.16 release info to the version index pages"
then pushed.

**Comment by LaurentGoderre** [comment]
Will merge as soon as the build passes

**Comment by MaximMartel** [comment]
Understood. Thank you.

**Pull request merged**
