### PR TITLE
Geomap: Fixed i18n issues.

### LINKED ISSUE #6707: Default base map (CBM) attribution links are broken
Broken links: 
 http://geogratis.gc.ca/geogratis/CBM_CBC?lang=en
 http://geogratis.gc.ca/geogratis/CBM_CBC?lang=fr
 
New links: 
 http://www.nrcan.gc.ca/earth-sciences/geography/topographic-information/free-data-geogratis/geogratis-web-services/17216#g3
 http://www.rncan.gc.ca/sciences-terre/geographie/information-topographique/donnees-gratuites-geogratis/services-web-geogratis/17294#g3

### PR DESCRIPTION
**Pull request by pjackson28**
Fixes #6707

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@pjackson28 looks like your pr deleted the file instead of updating it

**Comment by pjackson28** [comment]
@LaurentGoderre It's because the wget task failed. Here is the error message:
```
<HTML>
<HEAD>
<TITLE>Moved Temporarily</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Moved Temporarily</H1>
The document has moved <A HREF="https://docs.google.com/spreadsheets/d/1BmMrKN6Rtx-dwgPNEZD6AIAQdI4nNlyVVVCml0U594o/pub?gid=1&amp;output=csv">here</A>.
</BODY>
</HTML>
```
Could you please fix this?

**Comment by LaurentGoderre** [comment]
They changed their api.....

**Comment by LaurentGoderre** [comment]
Download and apply the following patch using `git apply GoogleDocs.patch`

https://gist.githubusercontent.com/LaurentGoderre/81fd2e0ec7f975190a9b/raw/3a904b1aa45326c90fd21b24d4fbcb865a7b4a4c/GoogleDocs.patch

**Comment by pjackson28** [comment]
Okay, I used <code>curl https://gist.githubusercontent.com/LaurentGoderre/81fd2e0ec7f975190a9b/raw/3a904b1aa45326c90fd21b24d4fbcb865a7b4a4c/GoogleDocs.patch | git apply -</code> to do it all at once.

**Pull request merged**
