### PR TITLE
Convert pagination to a list (DataTables)

### PR DESCRIPTION
**Pull request by ghost**
Please see https://github.com/wet-boew/wet-boew/issues/5912 for an example.

May require:
- [ ] Aria Controls
- [ ] Styling Updates

### CODE REVIEW

**Comment by kodecount** [comment]
May require more aria controls let me know and/or styling.

**Comment by shawnthompson** [comment]
#7937 has been merged, can you rebase and retest your change?

**Comment by shawnthompson** [comment]
https://shawnthompson.github.io/kodecount-tables-pagination/unmin/demos/tables/tables-en.html

**Review by lucas-hay — CHANGES_REQUESTED** [review]
Discussed in PR review meeting. @kodecount Can you change the "list-inline" class to "pagination mrgn-tp-0 mrgn-bttm-0". This will keep the look consistent with what it is now.

**Review by lucas-hay — APPROVED** [review]
Approved at PR review meeting.

**Pull request merged**
