### PR TITLE
Update wetsites-en.hbs

### PR DESCRIPTION
**Pull request by peterparkers**
change from http to https for website that supported https

### CODE REVIEW

**Review by duboisp — CHANGES_REQUESTED** [review]
Dont' work: https://news.gc.ca/
You can replace with: https://www.canada.ca/en/news.html or remove it as it now migrated on Canada.ca.

Don't work: https://www.cic.gc.ca/english/index.asp
You can replace with: https://www.canada.ca/en/services/immigration-citizenship.html or remove it as it now migrated on Canada.ca

Don't work: https://www.healthycanadians.gc.ca/
You can replace with: https://www.canada.ca/en/services/health.html or remove it as it now migrated on Canada.ca

To remove as they are not seems to use wet-boew framework anymore: https://ottawa.ca/en

To remove as they are not seems to use wet-boew framework anymore: https://www.collegesdelontario.ca/

**Comment by duboisp** [comment]
@peterparkers BTW - Thanks for your contribution

**Comment by duboisp** [comment]
@peterparkers Can I assume this PR is superseeded by #8224?

**Comment by peterparkers** [comment]
@duboisp yes, thanks you

**Pull request closed without merging**
