### PR TITLE
BROKEN: Add WhatsApp (Share Plugin)

### PR DESCRIPTION
**Pull request by ghost**
Allows WhatsApp as a share option.

### CODE REVIEW

**Comment by duboisp** [comment]
We would need to add the logo in the shared plugin CSS

**Review by duboisp — CHANGES_REQUESTED** [review]
We would need to add the logo in the shared plugin CSS

**Comment by thekodester** [comment]
I could not update the shared plugin CSS, it was being ignored by git, and seem to auto generate when I ran grunt.

**Comment by thekodester** [comment]
I ignored the git ignore and submitted the file.

**Comment by thekodester** [comment]
Actually looking at https://github.com/wet-boew/wet-boew/tree/master/src/plugins/share that css file is not even listed.

**Pull request closed without merging**
