### PR TITLE
Fix dependency loading with readiness issue

### PR DESCRIPTION
**Pull request by duboisp**
For testing this solution:

**wet-boew theme:**
* Working example index: http://universallabs.org/wet/labs/fixdeps-wet-boew/demos/index-en.html 
* Carousel: http://universallabs.org/wet/labs/fixdeps-wet-boew/demos/tabs/tabs-carousel-en.html
* Data Table: http://universallabs.org/wet/labs/fixdeps-wet-boew/demos/tables/tables-en.html

**GCWeb theme:**
* Working example index: http://universallabs.org/wet/labs/fixdeps-gcweb/unmin/demos/index-en.html 
* Carousel: http://universallabs.org/wet/labs/fixdeps-gcweb/unmin/demos/tabs/tabs-carousel-en.html
* Data Table: http://universallabs.org/wet/labs/fixdeps-gcweb/unmin/demos/tables/tables-en.html
* URL Mapping: http://universallabs.org/wet/labs/fixdeps-gcweb/unmin/demos/urlmapping/tblfilter-en.html

//cc @masterbee @MaximMartel @lucas-hay @thomasgohard

### CODE REVIEW

**Review by lucas-hay — APPROVED** [review]

**Comment by LaurentGoderre** [comment]
:-1: This is not the best way to do it because many plugins have events we can leverage that would require a lot less DOM operation and loop checking. This approach should be the last resort.

**Comment by lucas-hay** [comment]
@LaurentGoderre Do you have a quick fix?
We need this ASAP, so we are trying Pierre's solution, but can revert if/when another solution is developed.

**Comment by LaurentGoderre** [comment]
It can be a temporary fix but it's definitely not optimal

**Comment by duboisp** [comment]
@LaurentGoderre I agree with you this should be a temporary fix. As it was suggested by Mario before, a longer term solution could be to use requirejs instead of yepnope to load our library.

**Pull request merged**
