### PR TITLE
build: Bump grunt-sass@2

### PR DESCRIPTION
**Pull request by nschonni**
Allows prebuilt binaries on Node 8.
Comparing the diff of the built diffs there are a handful of minor precision differences in the built files.

Left in the package-lock.json to help with repeatable builds, but it could be excluded

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
We're not building on Node 8 yet but :+1:

**Comment by LaurentGoderre** [comment]
@nschonni did you don a diff of the built results to  see what difference there is between the two?

**Comment by nschonni** [comment]
@LaurentGoderre yes, from the overall comment, there was only a few precision differences with a few colour values in the final built CSS.

**Comment by LaurentGoderre** [comment]
Excellent!

**Review by LaurentGoderre — APPROVED** [review]

**Pull request merged**
