### PR TITLE
Switch to ESLint

### PR DESCRIPTION
**Pull request by nschonni**
Ran an automated conversion (via [PolyJuice](https://github.com/brenolf/polyjuice)) of the JSHint and JSCS configs and then cleaned up some broken code that ESLint was able to identify, but the old tools didn't.

There are many additional rules available http://eslint.org/docs/rules/ and IDE integrations http://eslint.org/docs/user-guide/integrations

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
So ESLint does the same that JSHint and JSCS did but in one? If so that is pretty cool!

@masterbee can we merge?

**Comment by masterbee** [comment]
@nschonni @LaurentGoderre - Totally agree, sorry it was so late to respond, was playing with ESLint for the past 2 weeks to get a feel for it robustness. It is really well done. 

@nschonni - can you look a the branch conflict and see if this can be adjusted to we can merge.

**Comment by nschonni** [comment]
Rebased

**Comment by nschonni** [comment]
Landing this now to avoid more rebases

**Pull request merged**
