### PR TITLE
Plugin Geomap: Added support for ESRI GeoJSON

### PR DESCRIPTION
**Pull request by jvanulde**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
You have a bunch of scss lint errors

**Comment by jvanulde** [comment]
I will fix those. I rely on grunt dist to catch these.

**Comment by LaurentGoderre** [comment]
unfortunately, scss-lint doesn't have a JS equivalent (it's in Ruby) and we don't want to force people to download it for one dependency

**Comment by jvanulde** [comment]
I don't understand why this error is thrown: ./src/plugins/geomap/_base.scss:191 [W] DeclarationOrder: Rule sets should start with @extend declarations, followed by properties and nested rule sets, in that order

**Comment by LaurentGoderre** [comment]
Declaration have to come before nested rules as such:

```scss
.olFramedCloudPopupContent {
	overflow: auto;
	padding: 5px;

	ol {
		@extend %olFramedCloudPopupContentFontSize;
	}
	p {
		@extend %olFramedCloudPopupContentFontSize;
	}
	ul {
		@extend %olFramedCloudPopupContentFontSize;
	}
 }
```

**Comment by pjackson28** [comment]
Please squash the commits and use the format Geomap: Added support for ESRI GeoJSON

**Comment by LaurentGoderre** [comment]
I can merge as soon as you squash those commits

**Comment by andre-gh** [comment]
Can this pull request be closed, has it gone stale?

**Comment by jvanulden** [comment]
When I find time I will resolve the conflicts and commit.

**Comment by hsrudnicki** [comment]
Please update this issue's status for this current year as well, thx

**Comment by jvanulde** [comment]
I will close this. Will address in future release.

**Pull request closed without merging**
