### PR TITLE
Create migrating

### PR DESCRIPTION
**Pull request by TouficS**
Here's a map of class name changes my team developed during our 3-to-4 transition.

### CODE REVIEW

**Comment by EricDunsworth** [comment]
Wow, cool page :)! Some of my colleagues were recently looking for a CSS class migration list and thought they'd be stuck starting from scratch. I bet it could still be useful to other departments to this day.

Since this PR seemed to be on the verge of completion and progress on it has completely died off for several months, would anyone mind if I tried finishing it off in separate PR? @thomasgohard I'd need your help to translate (or double-check a translation I come up with for) the documentation's link to the migration page.

**Comment by thomasgohard** [comment]
@EricDunsworth would love the help to get this one completed and merged in. Would we be able to do this at one of the upcoming code sprints?

**Comment by LaurentGoderre** [comment]
Note that tomorrow's code spriny is cancelled and next one is in Kanata so it might have to wait to the one after that

**Comment by andre-gh** [comment]
Can this pull request be closed, has it gone stale?

**Comment by andre-gh** [comment]
Due to going stale this pull request has been closed.  Please feel free to re-open and comment should you wish to continue development.

**Pull request closed without merging**
