### PR TITLE
Plugin Geomap: Added map loading progress indicator. 

### PR DESCRIPTION
**Pull request by jvanulde**
Initializes map height and show progress on initial load. Improves user experience in low-bandwidth scenarios.

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Alternatively, you could try using the `%global-loading` mixin to avoid bringing a new image

**Comment by jvanulde** [comment]
@LaurentGoderre can you point me to the docs for the %global-loading mixin?

**Comment by LaurentGoderre** [comment]
There isn't really any doc for it. You can however do

```
.geomap-progress {
    @extend %global-loading;
}
```

**Comment by jvanulde** [comment]
Tried that and nothing shows...

**Comment by LaurentGoderre** [comment]
really....weird.

**Comment by jvanulde** [comment]
Sorry it does work. Is there a way to customize the image?

**Comment by LaurentGoderre** [comment]
it's a glyphicon, not an image. You could modify it but the selection of glyph is limited

**Comment by pjackson28** [comment]
Please squash the commits and use the format Geomap: Added map loading progress indicator. Initialized map height and show...

**Comment by andre-gh** [comment]
Can this pull request be closed, has it gone stale?

**Comment by jvanulden** [comment]
Hasn't been merged yet...

**Comment by hsrudnicki** [comment]
Can be this merged/closed or otherwise? Please update this status as well for the current year, thank you

**Comment by jvanulde** [comment]
I will close this. It's been sitting around for too long. Will address in a future version.

**Pull request closed without merging**
