### PR TITLE
formvalid: Fix the issue with displaying duplicate validation errors …

### PR DESCRIPTION
**Pull request by rachelywang**
…if using require_from_group.

Issue #7067.

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
What is the reasoning behind this change?

**Comment by rachelywang** [comment]
If you use jQuery validation "require_from_group", the validation errors will be displayed multiple times.

**Comment by LaurentGoderre** [comment]
I know but how does breaking the caching of element fixes that?

**Comment by rachelywang** [comment]
I don't even know why use the caching of elements initially (from release notes of version 12: to fix the issue with a click on a summary link being ignored when focus is in a form field). I'm thinking it may relate to racing...

**Comment by pjackson28** [comment]
This may no longer be needed with the fix in PR #7161. Should check to see if that PR fixes the duplication issue before considering the merging in of this PR.

**Comment by masterbee** [comment]
closing since this is duplication P.R and has gone stale

**Pull request closed without merging**
