### PR TITLE
Reapply "Bower to npm"

### PR DESCRIPTION
**Pull request by nschonni**
Reverts the Revert in wet-boew/wet-boew#8228

### CODE REVIEW

**Comment by duboisp** [comment]
@nschonni what kind of update we need to apply for the theme build script?

**Comment by nschonni** [comment]
Not sure exactly, but I think mainly it comes from how the demos were using the jQuery version from the Bower file to generate the CDN links.

**Comment by LaurentGoderre** [comment]
It's a bit of a big change....

**Comment by duboisp** [comment]
Can, one of you, provide instructions on how we can apply that "big change" on every theme?

**Comment by LaurentGoderre** [comment]
I'm working on it

**Comment by duboisp** [comment]
As discussed at the technical review meeting, 

This PR are going to be merge and then new PR are going to be submitted to fix the build of GCweb, Intranet, GCWU and Base theme.

**Review by duboisp — APPROVED** [review]

**Comment by LaurentGoderre** [comment]
Note that this broke the release script. The team won't be able to use the script for next versions unless the script is fixed.

**Comment by duboisp** [comment]
@nschonni or @LaurentGoderre when do you thing the GCWeb build would be fixed. I have a some update that I would need to apply to GCweb template next week and I need the GCWeb to be working.

**Pull request merged**
