### PR TITLE
Bootstrap 4: Document p-sm-3/px-sm-3/mb-sm-5 classes

### PR DESCRIPTION
**Pull request by EricDunsworth**
Those classes have existed since #8738 but had never been documented until now.

### CODE REVIEW

**Comment by EricDunsworth** [comment]
Actually I just realized I overlooked the ``mb-sm-5`` class.

Just switched this PR to draft until I get around to sneaking it in :).

**Comment by duboisp** [comment]
Pre-approved once @EricDunsworth add the additional CSS, later today. + code review and local testing.

**Comment by EricDunsworth** [comment]
Just added ``mb-sm-5``. This PR should be ready to roll now :).

**Review by duboisp — APPROVED** [review]
Tested locally and work as expected.

Thanks @EricDunsworth for documenting those features.

**Pull request merged**
