### PR TITLE
Overlay Print - Only print the active dialog. Alternate solution of #7791

### LINKED ISSUE #7615: Overlay print issue
The content of overlay prints on top of the page content rendering both unreadable. This is the case with all types of overlays except Centred popup lightbox that is placed at the start of the page when printed.
It seams that WET4 removes all backgrounds for the print. Is it possible to keep background at least for full screen overlays? And maybe not even print the rest of the page?
Maybe exclude Left-panel, Right-panel, Top bar and Bottom bar from print all together like it's done for main nav, footer and search? Just a suggestion. 
It would be ideal for my current project if we would be able to print just the content of the full screen overlay and ignore the rest of the page. Any suggestions?

### PR DESCRIPTION
**Pull request by duboisp**
This should fix #7615

See the conversation on #7791 for more info.

Here PDF showing what it would look like when printed.
* [Centered popup](http://universallabs.org/wet/labs/temporary/center-popup.pdf)
* [Middle screen overlay](http://universallabs.org/wet/labs/temporary/middle-screen.pdf)
* [Full screen overvay](http://universallabs.org/wet/labs/temporary/full-screen.pdf)

It was tested on FF dev, Chrome and Edge

### CODE REVIEW

**Comment by kodecount** [comment]
This doesn't work with left or right panels. Since `.wb-overlay-open` is never added to them. Also user should have the ability to add a class `.no-print` that won't print the overlay. Like if it is a menu and is pointless to print.

**Comment by duboisp** [comment]
Do you think when the left and right panel content is displayed that it should be printed by default? May be something like your solution in #7791 where we have the content of the page with the content of the overlay when printing? What do you think?

Regarding the ```no-print``` class. I assume that if the user are currently viewing a dialog and then print the page, I assume that the expected behaviour is to print the dialog content. But I can see, a usage of the ```no-print``` class like if the content of the right or left panel are pointeless for printing. 

I do not think the content that is in the bottom and top bar should be printed as the usage are very close to a menu.

Make sense? 

If so I will add some additional instruction in the wb-overlay and in wb-lbx documentation about how printing is managed and when to use the "no-print" CSS class.

**Comment by kodecount** [comment]
Yes I agree. Top and Bottom bar well pretty much always be a menu. By default with out this PR they well print on top of the main content and makes it unreadable. So having them push to the bottom of the page I think is okay for these overlays and still printing the page content with them for content. As for my original code checkout [my comment](https://github.com/wet-boew/wet-boew/issues/7615#issuecomment-263626110) on issue.

**Comment by duboisp** [comment]
I merged my solution with the one of @kodecount provided in #7791.

Here PDF showing what it would look like

* [None open](http://universallabs.org/wet/labs/temporary/8dec-none-open.pdf)
* [Centred popup](http://universallabs.org/wet/labs/temporary/8dec-centred-popup.pdf)
* [Full screen](http://universallabs.org/wet/labs/temporary/8dec-full-screen.pdf)
* [Left panel](http://universallabs.org/wet/labs/temporary/8dec-left-panel.pdf)
* [Middle screen](http://universallabs.org/wet/labs/temporary/8dec-middle-screen.pdf)
* [Top bar](http://universallabs.org/wet/labs/temporary/8dec-top-bar.pdf)
* [Top bar with .no-print](http://universallabs.org/wet/labs/temporary/8dec-top-bar-with-no-print.pdf)

(ps. regarding the documentation of ```.no-print``` class, it will be done in a another PR with a couple of small fix. I plan to submit that PR this week-end or early next week.)

**Comment by duboisp** [comment]
@LaurentGoderre or @MaximMartel Do you have any concern or issue with this PR?

_Note: the ```noprint``` CSS class is already documented in the documentation of overlay plugin._

**Comment by duboisp** [comment]
@lucas-hay as discussed yesterday, I did the rebase and I fixed the conflict.

**Comment by LaurentGoderre** [comment]
This approach would break with the existing lightbox. If the lightbox moves to the content area it wouldn't be available at all.

**Comment by duboisp** [comment]
The SASS was adjusted in a way to not break with existing lightbox. To ensure it work, I will re-test it this afternoon to ensure that is not breaking.

**Comment by lucas-hay** [comment]
Pierre, let us know your results. This might be a little too last minute for this release.

**Comment by duboisp** [comment]
@lucas-hay I tested again and it didn't break the lightbox plugin.

**Comment by lucas-hay** [comment]
@LaurentGoderre and @duboisp 
Based our discussion of this two weeks ago, the rebase and conflict fix that was completed, and the testing today, should we merge this, or wait for the next release. I am on the fence for this one given how close to releasing we are.

**Comment by duboisp** [comment]
Me I think it is ok to merge this PR for this release. But it's up to you @lucas-hay

**Review by lucas-hay — DISMISSED** [review]
Approved at PR review meeting.

**Comment by duboisp** [comment]
[ ] Investigate if CSS can be used to prepend the page title when printing the dialog

**Comment by duboisp** [comment]
It seem that can be done by duplicating the page title text-node into an attribute of an HTML element. 
I will do a few test to see what output can be achieved.

**Comment by duboisp** [comment]
Closing in favor of #7803

**Pull request closed without merging**
