### PR TITLE
Horizontal lines in tables

### PR DESCRIPTION
**Pull request by ghost**
Fixes issue #7678 and #7703 please see [jsFiddle demo](https://jsfiddle.net/kpduncan/yrug8zm6/)

### CODE REVIEW

**Comment by kodecount** [comment]
@thai-po and @Sburbidge What are your guys input? Please see the fiddle.

**Comment by kodecount** [comment]
@duboisp This is based of the WET 3 horizontal line code you had.

@thai-po and @Sburbidge Also what your inputs? Please see the fiddle.

**Comment by duboisp** [comment]
@kodecount I do not understand the logic behind those CSS from a generalization point of view, as they set the same style
```th:nth-child(n+4)
th:nth-child(n+3)
th:nth-child(n+2)```

But I can understand if that sequence is specific fit the CSS need expressed in #7678

See my comment in https://github.com/wet-boew/wet-boew/issues/7678#issuecomment-259020369 to know how this issue can be addressed.

Cheers

**Comment by kodecount** [comment]
@duboisp They allow you to skip at least one or more `<td></td>` if the user wish to.

**Comment by duboisp** [comment]
@kodecount I understand, but what about of improving how complex table is styled with wb-zebra as being an alternative solution?

**Comment by kodecount** [comment]
@duboisp I'll look into it. If I get some time.

**Pull request closed without merging**
