### PR TITLE
Addresses issues #6678, #6750, #6665 by adding support for MapQuest O…

### PR DESCRIPTION
**Pull request by jvanulde**
…SM base map, and #6423.

Fixes:
#6678 #6750 #6665 #6423 #6830

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
To fix the build rewrite the following code

https://github.com/jvanulde/wet-boew/blob/geomap-enhancements/src/plugins/geomap/_base.scss#L143-L151

To: 

```
.olControlAttribution {
    p {

    }
}
```

**Comment by LaurentGoderre** [comment]
@jvanulde I added a list of related issue in your PR body so the related issues are closed when merging. Can you validate that they are all related.

**Comment by jvanulde** [comment]
Confirmed.

**Comment by hsrudnicki** [comment]
Just by occasion and the dependency, are you ready to close this issue?

**Comment by LaurentGoderre** [comment]
There seems to be a merge conflict now

**Comment by LaurentGoderre** [comment]
Can you fix and I will merge in the next release

**Pull request merged**
