### PR TITLE
Tabbed Interface: Documentation Typo

### PR DESCRIPTION
**Pull request by codejunkyard**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
You have another unrelated commit in your PR. You should create a new branch and cherry-pick only the commit you want

**Comment by shawnthompson** [comment]
@GabrielVautour, let me know if you need help doing that.

**Comment by LaurentGoderre** [comment]
@duboisp could you create a new pr with this? And reviews if it's accurate too

**Comment by duboisp** [comment]
@LaurentGoderre PR submitted see #7773 and it was still accurate.

**Pull request closed without merging**
