### PR TITLE
Used netrc for CI auth

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@lucas-hay this will need to be applied to every repo

@EricDunsworth do you have time to help with this?

**Comment by EricDunsworth** [comment]
@LaurentGoderre I can can try quickly replicating this PR's changes in WET's other theme repos right now, but don't think I have capacity to test them all individually.

Can I proceed immediately, or should we wait until @nschonni chimes in?

**Comment by nschonni** [comment]
Is this related to https://blog.travis-ci.com/2017-05-08-security-advisory? Otherwise I'm not sure what this adds

**Comment by EricDunsworth** [comment]
Btw I've got a whole slate of commits ready, but aren't sure whether it's worth sending them out yet. Gonna see where this PR's discussion leads to before opening any other PRs.

Above @nschonni's most recent comment, there's a notification about a commit I fired up on my GCWeb fork earlier. That commit represents what all my PRs will be like.

**Comment by LaurentGoderre** [comment]
@nschonni the token has been revoked and we need to change all of them. This helps towards that.

**Comment by EricDunsworth** [comment]
I'm gonna go ahead and open up all my PRs.

**Comment by LaurentGoderre** [comment]
Awsome! Thanks @EricDunsworth

**Comment by LaurentGoderre** [comment]
I think we also nee to update the styleguide

**Comment by LaurentGoderre** [comment]
Note that no build will pass until this is merged

**Comment by EricDunsworth** [comment]
@LaurentGoderre FYI wet-boew/wet-boew-styleguide#339 :).

**Comment by lucas-hay** [comment]
@LaurentGoderre, @EricDunsworth are these good to merge now?

**Comment by LaurentGoderre** [comment]
I think so

**Review by lucas-hay — APPROVED** [review]

**Comment by EricDunsworth** [comment]
@lucas-hay I just noticed I missed a comma-less instance of ``silent: true`` in my other PRs. I'll update them in a moment, then follow-up.

**Comment by EricDunsworth** [comment]
I've updated all of my other PRs. They're basically exact replicas of this one.

Specifically, they add ``before_install:  - echo "machine github.com login $GH_TOKEN" >> ~/.netrc`` to travis.yml and remove all instances of ``silent: true`` and ``silent: true,`` from Gruntfile.coffee.

**Pull request merged**
