### PR TITLE
added important to border removals because of specificity restraint

### PR DESCRIPTION
**Pull request by shawnthompson**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
tsk tsk tsk...slippery slope....

**Comment by shawnthompson** [comment]
I was going to put it in the theme but there are a few places where we want to remove the borders of an element, like details / summary and another one I can't remember right now, which I overwrote in the theme CSS and removed the borders. I think this is a good case where `!important` is used properly.

**Comment by LaurentGoderre** [comment]
Make sure it doesn't start proliferating ;)

**Comment by masterbee** [comment]
@LaurentGoderre +1 love the proliferating..

**Comment by shawnthompson** [comment]
Can someone merge this?

**Comment by shawnthompson** [comment]
Thanks! :+1:

**Pull request merged**
