### PR TITLE
Replace Bitly with TinyURL (Share Plugin)

### PR DESCRIPTION
**Pull request by ghost**
Allows short url without having to make an account (Bitly requires an account now).

### CODE REVIEW

**Comment by duboisp** [comment]
Why we should replace bit.ly by tinyURL?

**Comment by delisma** [comment]
@thekodester could we just add TinyURL as an option? That way we don't break the plugin for those who have a bit.ly account.
> Why we should replace bit.ly by tinyURL?

**Comment by thekodester** [comment]
The bit.ly link doesn't do anything any more. It just takes you to the bit.ly website.

**Comment by thekodester** [comment]
I created a free account and tried the url and it does nothing.

https://bitly.com/a/bitmarklet?u=https%3A%2F%2Fwet-boew.github.io%2Fwet-boew%2Fdemos%2Fshare%2Fshare-en.html

**Review by duboisp — APPROVED** [review]

**Comment by duboisp** [comment]
Thanks for the explanation @thekodester

**Pull request merged**
