### PR TITLE
Multimedia Player: add transcript highlighting feature to inline captions

### PR DESCRIPTION
**Pull request by crichard**
/cc @LaurentGoderre 
Not sure if I did this PR right (how do I split the two commits?)  ... but can you take a look at the multimedia player portion of this and let me know if any adjustments are required to make this usable.  Merci.

### CODE REVIEW

**Comment by pjackson28** [comment]
Please resolve the merge conflicts.

**Comment by andre-gh** [comment]
Can this pull request be closed, has it gone stale?

**Comment by LaurentGoderre** [comment]
This is still a nice to have enhancement

**Comment by hsrudnicki** [comment]
Can be this closed or otherwise? Please update the status of this again for the current year, thank you

**Comment by LaurentGoderre** [comment]
Closing since there's a more recent one

**Pull request closed without merging**
