### PR TITLE
Build: Bump grunt-sass to 1.0.0

### PR DESCRIPTION
**Pull request by nschonni**
I used KDiff3 to compare the dist outputs from the grunt/node-sass to the last build from the wet-boew-dist, and here is what I noticed:
- rgba(0, 0, 0, 0) to "transparent"
- single quotes to double in some cases
- selectors moved to new lines
- `@charset "UTF-8"` added automatically if it wasn't added manually
- strip leading zeros from values
- second green digit rounded down in some cases in the `.text-` classes in Bootrap. This may just be a precision difference for the `darken($color, 10%)`, since there is no difference to things like the grids
- removed media query blocks that contain only comments
- removed duplicate selectors when found on a class declaration. Ex: `.foo, bar, .foo` becomes `.foo, bar`

### CODE REVIEW

**Comment by nschonni** [comment]
This also means people can run the build with Node 0.10 , 0.12, or iojs since the old node-sass dependency only shiped binaries for 0.10.

**Comment by LaurentGoderre** [comment]
:+1: Thanks for taking the time for making the diff. I think we should merge in v4.0.17 since v4.0.16 comes out next Tuesday and if this changes something, it doesn't give us much time to catch it.

**Comment by LaurentGoderre** [comment]
Can you create a gist for the difference?

**Comment by LaurentGoderre** [comment]
Fixes #6770

**Comment by EricDunsworth** [comment]
Btw thanks :)!

**Comment by LaurentGoderre** [comment]
Here is the diff https://gist.github.com/LaurentGoderre/a2521cf8c75ce336eb3e

**Comment by LaurentGoderre** [comment]
Perhaps it's time to revisit those TODOs and try to implement `@extend` where we couldn't before.

**Pull request merged**
