### PR TITLE
Steps form: Add type to next previous buttons

### PR DESCRIPTION
**Pull request by andrewdp**
Fix: The default WET action on pressing Enter in an input field is to trigger a click event on the first submit type button located on the form. Since the first button on a step form is often the generated "next" button on the first step and no type is specified for this button the form will open to the second step. Specifying the button type should fix this issue.

### CODE REVIEW

**Comment by GormFrank** [comment]
**To do:**
- [ ] Build and test locally (@duboisp)

Pre-approved upon successful completion of "To do" above.

**Comment by duboisp** [comment]
I tested locally and work as expected. Once the eslint error is fixed this PR can be merged.

@andrewdp: There is two small eslint issue which is to add spacing in the function call.

ref. https://contribute.jquery.org/style-guide/js/#spacing

**Comment by andrewdp** [comment]
Ok The spacing on the brackets has been added.

**Comment by duboisp** [comment]
Pre-approved upon successful completion of successful build and testing.

It's ok from a code review perspective

**Review by duboisp — APPROVED** [review]

**Comment by duboisp** [comment]
I builded and tested locally. 
It works as expected and make the produced HTML code compliant to specification because the default type for a button is submit which is not the case here. Reference: https://html.spec.whatwg.org/multipage/form-elements.html#attr-button-type

Thanks @andrewdp for fixing that issue.

**Pull request merged**
