### PR TITLE
Tabbed interface: Update for a11y code

### LINKED ISSUE #6693: Tabbed Interface - Carousel: use of alternative text
For the carousel code example, I think we should be making the link text / alternative text more descriptive and more accessible. 

**Before**
``` html
<h2 id="carousel-s1">Carousel style 1 example (<code>carousel-s1</code>)</h2>
<div class="wb-tabs carousel-s1">
<ul role="tablist">
<li class="active"><a href="#panel1">Tab 1</a></li>
<li><a href="#panel2">Tab 2</a></li>
<li><a href="#panel3">Tab 3</a></li>
</ul>
<div class="tabpanels">
<div role="tabpanel" id="panel1" class="in fade">
<a href="http://www.tc.gc.ca/eng/civilaviation/opssvs/general-personnel-changes-1814.htm">
<figure>
<img src="img/protect-environment.jpg" alt="Panel 1" />
<figcaption>
<p>Take Note: Renewal of the Aviation Document Booklet.</p>
</figcaption>
</figure>
</a>
</div>
<div role="tabpanel" id="panel2" class="out fade">
<a href="http://www.tc.gc.ca/eng/railsafety/publications-46.htm">
<figure>
<img src="img/banff.jpg" alt="Panel 2" />
<figcaption>
<p>Take Note: Grade Crossing Improvement Program (GCIP).</p>
</figcaption>
</figure>
</a>
</div>
<div role="tabpanel" id="panel3" class="out fade">
<a href="http://www.tc.gc.ca/eng/tankersafetyexpertpanel/menu.htm">
<figure>
<img src="img/investinourfuture.jpg" alt="Panel 3" />
<figcaption>
<p>Take Note: Tanker Safety Expert Panel.</p>
</figcaption>
</figure>
</a>
</div>
</div>
</div>
```

**After**
``` html
<h2 id="carousel-s1">Carousel style 1 example (<code>carousel-s1</code>)</h2>
<div class="wb-tabs carousel-s1">
<ul role="tablist">
<li class="active"><a href="#panel1">Tab 1: Take Note: Renewal of the Aviation Document Booklet.</a></li>
<li><a href="#panel2">Tab 2: Take Note: Grade Crossing Improvement Program (GCIP).</a></li>
<li><a href="#panel3">Tab 3: Take Note: Tanker Safety Expert Panel.</a></li>
</ul>
<div class="tabpanels">
<div role="tabpanel" id="panel1" class="in fade">
<a href="http://www.tc.gc.ca/eng/civilaviation/opssvs/general-personnel-changes-1814.htm">
<figure>
<img alt="" src="img/protect-environment.jpg" />
<figcaption>
<p>Take Note: Renewal of the Aviation Document Booklet.</p>
</figcaption>
</figure>
</a>
</div>
<div role="tabpanel" id="panel2" class="out fade">
<a href="http://www.tc.gc.ca/eng/railsafety/publications-46.htm">
<figure>
<img alt="" src="img/banff.jpg" />
<figcaption>
<p>Take Note: Grade Crossing Improvement Program (GCIP).</p>
</figcaption>
</figure>
</a>
</div>
<div role="tabpanel" id="panel3" class="out fade">
<a href="http://www.tc.gc.ca/eng/tankersafetyexpertpanel/menu.htm">
<figure>
<img alt="" src="img/investinourfuture.jpg" />
<figcaption>
<p>Take Note: Tanker Safety Expert Panel.</p>
</figcaption>
</figure>
</a>
</div>
</div>
</div>
```

* added the text from the paragraph to the the link text in the `li` in the `.tablist`
* removed the `alt` text in the `tabpanel` because the image is wrapped with an `a` which includes the `p` below it as link text

Was thinking of adding the Tab # to the `p` inside the image with `.wb-inv` but wasn't sure if it was needed.

`<p><span class="wb-inv">Tab 2: </span>Take Note: Grade Crossing Improvement Program (GCIP).</p>`

CC: @rlambert27, @MRicher, @lucas-hay, @masterbee

### PR DESCRIPTION
**Pull request by rlambert27**
Improved the LI text for panels and removed alt text for the pictures. Fixes #6693.

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Weird, the build fails because it think it doesn't have any alt. Can you moved the lat back to the end of the tag to see if it fixes it?

**Comment by rlambert27** [comment]
Fixed :-)

**Comment by rlambert27** [comment]
@LaurentGoderre Failed again :-( @EricDunsworth is suggesting it may be failing because it actually wants a value in the alt? Looks good to me though.

**Comment by LaurentGoderre** [comment]
If so that is a pretty big bug. Unfortunately we can't merge anything that breaks the build. I will have to investigate

**Comment by LaurentGoderre** [comment]
We will need this to land before we can merge

https://github.com/gjtorikian/html-proofer/pull/196

**Comment by wolfgang42** [comment]
I would also note that gjtorikian/html-proofer#196 requires you to pass `--alt_empty_ignore` to `htmlproof`; this preserves backward compatibility.

You can apply this patch to your `Gemfile`, if you're really eager to get it working:
```diff
-gem "html-proofer"
+gem 'html-proofer', :git => 'https://github.com/wolfgang42/html-proofer.git', :branch => 'alt-empty-ignore'
```

**Comment by LaurentGoderre** [comment]
@wolfgang42 thanks! I'm a bit hesitant since Ruby is not really part of our stack except for this one and sass-lint so I'd rather wait until it lands.

**Comment by andre-gh** [comment]
Can this pull request be closed, has it gone stale?

**Comment by andre-gh** [comment]
Due to going stale this pull request has been closed.  Please feel free to re-open and comment should you wish to continue development.

**Comment by shawnthompson** [comment]
We need to reopen this, this should have been merged. This is an accessibility improvement.
@rlambert27 @EricDunsworth can we tr to build this and see if it works know?
I'm going to have to make the same fix on GCWeb

**Comment by shawnthompson** [comment]
@andre-gh: Rebasing didn't work... I'm curious why GCWeb is using emprty alt attributes and it passes but wet-boew isn't allowed to use them in the validation?

**Comment by andre-gh** [comment]
Not sure, they both seem to ask for `html-proofer` on the ruby side of things.  I will have to take a deeper look.

**Comment by andre-gh** [comment]
@shawnthompson There are two things going on, the GCWeb repo is not instructing travis to run `bundle exec rake` (compare the `travis_script` in the `package.conf`s).  The second thing is that we need to update `html-proofer` to at-least `2.2.0` and add the option `ignore-empty-alt`.

@shawnthompson You have a ruby setup? Could you try that out for me?

**Comment by shawnthompson** [comment]
I'll give it a try tomorrow when I'm in the office. 

Shawn Thompson 
Plansmash@me.com

**Comment by andre-gh** [comment]
Thanks

**Comment by hsrudnicki** [comment]
When applicable, please update the status of this issue, which is referenced with the other issues?

**Comment by shawnthompson** [comment]
Ok, I will redo this PR and rebuild it correctly. This has been pending too long.

**Comment by shawnthompson** [comment]
@rlambert27 Have a look here and let me know if these are your changes:

http://shawnthompson.github.io/tabsa11y/demos/tabs/tabs-carousel-en.html

**Comment by rlambert27** [comment]
Yep looks good.

**Comment by shawnthompson** [comment]
Will close this once my PR passes

**Comment by EricDunsworth** [comment]
@shawnthompson Is PR #7407 an exact copy of this one? Both are currently failing :(.

I haven't tried experimenting on my end, but you probably need to add this after [line 23 in wet-boew/Rakefile](https://github.com/wet-boew/wet-boew/blob/master/Rakefile#L23):
```
		:empty_alt_ignore => true,
```

Once that's done and committed to master, I presume Travis-CI will automatically rebuild and hopefully pass. Since this PR is the original one, it'd probably be best to merge it in (instead of #7407).

**Comment by EricDunsworth** [comment]
FWIW, I've opened PR #7409 to add what I suggested in my previous post.

**Comment by shawnthompson** [comment]
I'm adding it to my PR. Let's see if it passes

**Comment by EricDunsworth** [comment]
@shawnthompson The suspense is killing me :P lol.

**Comment by LaurentGoderre** [comment]
You can rebase on top of master and it should work.

**Comment by shawnthompson** [comment]
@rlambert27, you want to rebase this? I can help you do it. If I can ever log into the network at work!!!

**Comment by shawnthompson** [comment]
YAY this passed!!!

**Comment by EricDunsworth** [comment]
@shawnthompson Awesome :).

**Comment by rlambert27** [comment]
Great work @shawnthompson !

**Pull request merged**
