### PR TITLE
Add print to overlays (Needs Testing)

### PR DESCRIPTION
**Pull request by ghost**
Fix issue #7615 

This setups overlays to print by default and to disable print must add `no-print` class (this could be changed to the opposite effect if required).

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Can you replace all the spaces with tabs? You should use the editorconfig plugin for it so you don't need to worry about it

**Comment by kodecount** [comment]
Sorry the power went out. Get to it later.

**Comment by kodecount** [comment]
@LaurentGoderre Can't seem to get editorconfig working.

**Comment by LaurentGoderre** [comment]
What is your issue?

**Comment by kodecount** [comment]
bug

**Comment by kodecount** [comment]
bug

**Comment by LaurentGoderre** [comment]
I disabled my whitespace plugin I think

**Comment by kodecount** [comment]
@LaurentGoderre Thanks for help I had too enable a indent/white-space indicator and remove white-space manually.

**Comment by duboisp** [comment]
I test it and all the overlay fragment coded in the page are showing where it was coded, that in the print view. 

I think it is expected to show only the active open overlay not all of them isn't it?

Here what it look like in PDF:
* [Currently in WET, when a middle screen overlay is open](http://universallabs.org/wet/labs/temporary/current-middlesceen-overlay.pdf)
* [This fix, when a middle screen overlay is open](http://universallabs.org/wet/labs/temporary/PR7791-middlescreen-overlay.pdf)
* [Currently in WET, when a full screen overlay is open](http://universallabs.org/wet/labs/temporary/current-fullscreen-overlay.pdf)
* [This fix, when a full screen overlay is open](http://universallabs.org/wet/labs/temporary/PR7791-fullscreen-overlay.pdf)
* [This fix, when a center popup is open](http://universallabs.org/wet/labs/temporary/PR7791-centerpopup-overlay.pdf)

@kodecount do you think it is feasible to only show the active overlay when printing?
I think that is behavior the user will expect to get when printing an active overlay. 

Just an idea regarding the location. I do not know if it will worth to update the overlay plugin to toggle a class in the ```html``` element when an overlay is open. May be that could help to better manipulate the print CSS when printing an open overlay and to hide the rest of the page content.

**Comment by kodecount** [comment]
@duboisp Yes and no. The problem that occurs when trying to hide the page contents is if the overlay is located in the `<main>` (that and it is also dependent on if the user who codes the page put all the content in the `<main>`) cause when you try to hide the page contents you hide the overlay in some cases.

As for only printing the active overlay I say that is possible. We probably use the `.open` class to determine if the modal is open and as before if the user doesn't want that modal to print they just add the `.no-print` class.

**Comment by kodecount** [comment]
@duboisp Code was updated to print only the active overlay with the page content.

**Comment by duboisp** [comment]
@kodecount sorry I forget to put the PDF file on my server.

By modifying slightly the wb-lbx and wb-overlay plugin, I found a way to only print the active overlay/popup  preceded by the page header and the page title (h1). Also I moved the popup opened with wb-lbx after the h1 where it's now provide more context when printed.

**Pull request closed without merging**
