### PR TITLE
Overlay CSS Fix (IE11)

### PR DESCRIPTION
**Pull request by ghost**
Fix is related to issue #7688 and based off @Christopher-O suggestion

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
I don't like the idea of putting in CSS hacks as a permanent solution

**Comment by duboisp** [comment]
@LaurentGoderre I do not like CSS hacks either, but what kind of solution do yo suggest instead? Do you think, the use case (#7688) that support that fix require more research and documentation?

**Comment by LaurentGoderre** [comment]
I think we should investigate further

**Review by duboisp — DISMISSED** [review]
The use case #7688 require further investigation. The goal is to avoid to use any CSS hack

**Comment by cfarquharson** [comment]
@LaurentGoderre who is going to investigate this?  I fear that by delaying the addition of the CSS and saying it will be 'investigated', that no one will do it and then there will be no solution and IE will continue to display the overlay incorrectly.

**Comment by Christopher-O** [comment]
As stated in #7688 the injected code was due to an inability to adjust the current CSS to fix the problem in IE.  Any fix that was done would then "break" the CSS in Firefox.

**Comment by LaurentGoderre** [comment]
The opposite can be said as well, if dirty code gets in, it may stay there for a long time.

**Comment by duboisp** [comment]
Test OK. I was able to reproduce the issue and this PR fix it.

close #7688

**Comment by LaurentGoderre** [comment]
Much better !

**Pull request merged**
