### PR TITLE
Add WhatsApp (Share Plugin)

### PR DESCRIPTION
**Pull request by ghost**
Allows WhatsApp as a share option. CSS not include as it appears to be auto generated and is not list here https://github.com/wet-boew/wet-boew/tree/master/src/plugins/share.

### CODE REVIEW

**Comment by duboisp** [comment]
@thekodester Can you add the icon/logo of what apps? You can just add the logo in this folder: ```src/plugins/share/sprites/```

**Review by duboisp — CHANGES_REQUESTED** [review]
Add the WhatsApp logo

**Comment by thekodester** [comment]
The what'sapp logo is already added.

**Comment by thekodester** [comment]
https://github.com/wet-boew/wet-boew/blob/875a2ade32b16c288f175f49f6da577abc06432f/src/plugins/share/sprites/whatsapp.png

**Review by duboisp — APPROVED** [review]

**Pull request merged**
