### PR TITLE
Multimedia player: Increased specifity of keyboard shortcuts and fixed space key shortcut issues.

### PR DESCRIPTION
**Pull request by EricDunsworth**
- Limits the scope of the player's keyboard shortcurts to the video element and the player's controls. This prevents conflicts with other elements situated within the same figure element as the player (such as transcript details/summaries and cuepoint buttons).
- Allows the space key to be used to activate the mute/unmute and closed caption buttons. Pressing space on volume control will also mutes/unmute.
- Limits the scope of the space key shortcut for playing/resuming to the video element, play/pause button and progress bar.

CC @LaurentGoderre @rlambert27 @andrewnordlund @nicolasraymond

### CODE REVIEW

**Comment by EricDunsworth** [comment]
Btw it doesn't look like any of this PR's changes caused Travis-CI to fail. Seems like it failed to setup its build system.

**Comment by LaurentGoderre** [comment]
Why was this merged?? I'm not sure this is what's best for accessibility. Has this been tested?

**Comment by shawnthompson** [comment]
@EricDunsworth said this was a request from @rlambert27's accessibility team. Can you folks confirm that this?

**Comment by rlambert27** [comment]
I remember there was an open issue on Github for this, can't seem to find it. @EricDunsworth do you remember what it was?

**Comment by LaurentGoderre** [comment]
The issue about accessibility was that it was confusing when multiple players were on the page that it was difficult to know which one was which.

When changing merging a PR that changes the existing behavior of a plugin in the name of accessibility, the AWG should at least test it before it is merged.

**Comment by shawnthompson** [comment]
And how are they supposed to test it? Pull the PR and build it locally? That seems like a lot of work to get a test on a change. Would there be a way to deploy a gh-pages version of each PR?

**Comment by LaurentGoderre** [comment]
Every PR seems excessive but perhaps there can be something setup for the purpose of testing some PRs. We can't not do it because it's inconvenient.

**Comment by shawnthompson** [comment]
but there's 22 pending PRs, why aren't they being merged?

**Comment by kodecount** [comment]
@shawnthompson I agree the long approval wait times is probably turning people off from even starting a PR request. For example the issue with feeds no longer supporting Facebook (since they ended the support) and the PR request to fix the issue with a Feed just for Facebook.

**Comment by EricDunsworth** [comment]
The reason I created this PR was because media player implementations that contained details/summary for transcripts previously weren't working properly. Focusing onto a summary, then pressing space was causing videos to play/pause instead of expanding/collapsing the details. This affected the [third example on the media player demo page](http://wet-boew.github.io/v4.0-ci/demos/multimedia/multimedia-youtube-en.html) and some pages on our departmental site. The same issue affected cuepoint links and other media player controls that use buttons. This was happening because the scope of the media player's keyboard controls spanned the player's entire figure element, which has the potential of conflicting with elements/plugins/polyfills that aren't meant to directly control the player.

From what I researched, it's normally supposed to be possible to press buttons via the space key and some screen readers (like JAWS) apparently even explicitly announce that space can be used to press buttons. So I ended up further restricting the scope of the space key for playing/pausing except for things that I'd consider to lend themselves to it (like the video element, play/pause button and timeline). I also added space key support for all of the player's controls (not just buttons).

@LaurentGoderre I don't have screen readers at my disposal, but I tested it out on my end and did some research in the lead-up to sending this PR.

@rlambert27 I'm not aware of any GitHub issues that have previously brought this up. I became aware of it via one of your team's WCAG 2.0 assessments on one of our site's pages.

**Comment by LaurentGoderre** [comment]
@EricDunsworth I am concerned that it is too restrictive. It very possible it needed to be abit more specific but the pattern of pressing space anywhere in a player for pausing is a common one. This is not a matter of wheter it works or not but this might make it much harder for screen reader to pause a video by forcing them to find the right button to pause it.

**Comment by EricDunsworth** [comment]
@LaurentGoderre Do you happen to have any reputable source(s) regarding the space key being commonly used for pausing anywhere inside a video player?

My intent wasn't to hurt the media player's accessibility with this PR. But since the main issue I was trying to fix involved pressing the space key on summary elements (which are interpreted as buttons), I figured it would also make sense and benefit accessibility for the space key to trigger most controls in the player - especially since most of them are buttons.

YouTube's HTML5 player is probably by far the most dominant media player on the web. It uses tons of ARIA roles and can be navigated with a keyboard. In that player, pressing the space key will play/pause videos when focused on the player as a whole, the seek slider, the play/pause button and the volume slider. However, when focused on the next, mute, settings, theater and full screen buttons, pressing the space key will trigger those controls (instead of playing/pausing the video). Some of this PR's changes made WET's media player work in a very similar manner.

Just to give a few sources that back up my stance about buttons and the space key:
* In the [button section of the W3C's WAI-ARIA Authoring Practices 1.1 guide](https://www.w3.org/TR/wai-aria-practices/#button), it states that space and Enter keys should be used to activate buttons. 
* [MDN's using the button role page](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role) claims that buttons are expected to be triggered with the space key.
* The [Paciello Group's ARIA Toggle Button examples](http://files.paciellogroup.com/blogmisc/ARIA/togglebutton.html) and [Max Design's role="button" examples](http://maxdesign.com.au/jobs/sample-accessibility/05-forms/attribute-role-buttons.html) indicate that when JAWS encounters buttons, it announces "[Button's name]. Button. To activate press space bar". Prior to this PR, that announcement would've been misleading in WET's media player, since the space key was previously playing/pausing instead of pressing focused buttons.

Thoughts? Would there be value in opening a dedicated issue regarding this?

**Comment by LaurentGoderre** [comment]
I'd like @SBleeks and @dfarough opinion on this

**Comment by SBleeks** [comment]
If a button is given focus, pressing spacebar or Enter should action that button.  
Looking at the youtube player: Within the player, spacebar does toggle the play/pause functionality. Uparrow increases volume, Downarrow decreases volume and letter M mutes sound, Leftarrow rewinds, and Rightarrow fastforwards. As a screen reader user, if I turn forms mode oon and move focus to a button (whether it is play, rewind, or mute, I expect the spacebar or Enhter keys to trigger that button.
Note: In the youtube player, forms mode must be off for the spacebar to act as a play/pause toggle.

**Pull request merged**
