### PR TITLE
Updated the i18n files with Inuktitut

### LINKED ISSUE #7033: Aboriginal Languages / Langues autochtones
I'm looking at http://wet-boew.github.io/wet-boew/index-en.html
Under "multilingual": 33 languages, but no sign of Aboriginal languages.

Je regarde http://wet-boew.github.io/wet-boew/index-fr.html
Sous "multilingue": 33 langues mais aucun signe des langue autochtones

### PR DESCRIPTION
**Pull request by LaurentGoderre**
Thanks @Bgolden67 for the translations

Fixes #7033

### CODE REVIEW

**Comment by nschonni** [comment]
Looks like it's choking on the Twitter URL https://travis-ci.org/wet-boew/wet-boew/builds/175727134#L1494 but I doubt that really is an i18n-able thing anyway

**Comment by LaurentGoderre** [comment]
:( not as straightforward as I would have hoped

**Comment by kodecount** [comment]
Yeah not supported: https://dev.twitter.com/web/overview/languages

**Comment by LaurentGoderre** [comment]
I'm removing the offeding string. However, I am wondering if it's there by mistake

/cc @Bgolden67

**Comment by LaurentGoderre** [comment]
@Bgolden67 this string was used in the Twitter name `ᑐᐃᖓᔪᖅ ᒐᕙᒪᒃᑯᑦ ᐋᕿᒃᓱᖅᓯᒪᕕᖓᓄᑦ ᑐᑭᖃᐅᑎ` was it there by error?

**Comment by LaurentGoderre** [comment]
@Bgolden67 there's also an issue with the string `[MIXIN] match(es) found`. The `[MIXIN]` needs to be there explicitly where the number should appear.

**Comment by LaurentGoderre** [comment]
@Bgolden67 there's also an issue with the geogratis URL (Line 187 of the sheet)

**Comment by LaurentGoderre** [comment]
I have removed the values on line 187 and 263 but it seems there are other issues

**Comment by LaurentGoderre** [comment]
Ok, I have to remove the translation for `about` since it's linking to an english page (Line 315)

**Comment by LaurentGoderre** [comment]
I also have to remove the value on Line 182

**Comment by LaurentGoderre** [comment]
Actually, it seems like row 182,183 and 184 or offset by one and should be moved down one

**Comment by LaurentGoderre** [comment]
I used @Bgolden67 source file to resolve most of the issue, seems like a lot of strings were out of alignment.. I'm still waiting on 4 translations.

**Comment by Bgolden67** [comment]
Thanks @LaurentGoderre I'm still waiting on the response back from the request we made Friday. As mentioned, getting Inuktitut translated is never quick

**Pull request merged**
