### PR TITLE
Bootstrap 4: Add sizing and flexbox related utilities

### PR DESCRIPTION
**Pull request by GormFrank**
## What does this pull request (PR) do? / Que fait cette demande « pull » (PR)?
Adds the following utilities from Bootstrap 4:
- `mt-auto`
- `h-100`
- `flex-column`

This PR enables [GCWeb PR #2034](https://github.com/wet-boew/GCWeb/pull/2034)

### CODE REVIEW

**Review by duboisp — CHANGES_REQUESTED** [review]
I fully reviewed and tested the code, it works as expected. There is only one editorial change to make.

Side note: We should remove to use "!important" since this is not relevant anymore because the bootstrap utility are inserted at the end of our CSS file (for WET-BOEW and for GCWeb) since our CSS includes re-org last year.

Todo:
* [x] Optional - Remove `!important` on at least the newly added CSS class
* [x] Fix the French table of content that are missing 1 link.

**Comment by duboisp** [comment]
Pre-approve at the technical review, upon the request change is completed

**Comment by GormFrank** [comment]
Keeping `!important` to stay consistent with other Bootstrap 4 utilities with ported.

**Review by duboisp — APPROVED** [review]
Reviewed the code and re-tested locally. Work as expected.

**Pull request merged**
