### PR TITLE
Carousel: Modify working example to show whole panels as clickable

### PR DESCRIPTION
**Pull request by thomasgohard**
cc/@masterbee

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
This involves a markup change doesn't it? It might be too late for this version but we can merge this immediately after v4.0.11 goes out

**Comment by shawnthompson** [comment]
@thomasgohard From a usability side, does this mean all carousels will be fully clickable no matter what? Do we have the option of only making the link text clickable?

cc/ @pcwsmith @DK-TBS @lucas-hay

**Comment by LaurentGoderre** [comment]
The markup change may be an issue as well...it should work both ways

**Comment by LaurentGoderre** [comment]
We can't merge as is because it doesn't respect the proper use of variables etc. I will open a seperate PR to address the CSS changes

**Comment by LaurentGoderre** [comment]
@thomasgohard please rebase this PR to exclude the second commit

**Comment by thomasgohard** [comment]
@shawnthompson @pcwsmith @DK-TBS @lucas-hay @LaurentGoderre both options can be used: full panel or caption-only. The only thing I changed is that the default example shows the full panel being clickable at @masterbee's request.

**Comment by thomasgohard** [comment]
@LaurentGoderre removed the CSS commit. This should be good to merge once the build is finished.

**Comment by shawnthompson** [comment]
@thomasgohard from a usability perspective would it be a good idea to use both options? On some carousels you can click the full panel and on others it's just the title caption?

**Comment by thomasgohard** [comment]
@shawnthompson from a usability perspective, you should be consistent. Both options are valid. But you should not mix both options on one Web site. Use one or the other.

**Comment by shawnthompson** [comment]
Perfect thanks

**Pull request merged**
