### PR TITLE
Roadmap update - Noted that IE8 and IE9 is no longer supported

### PR DESCRIPTION
**Pull request by TTVXStarWake**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Just rebase ;)

**Comment by MaximMartel** [comment]
the rebase isnt working...

**Comment by LaurentGoderre** [comment]
What error do you get?

**Comment by shawnthompson** [comment]
Current branch is up to date

**Comment by shawnthompson** [comment]
``` git
git checkout master
git reset --hard upstream/master
git checkout RoadmapUpdate
git rebase master
git rebase -i HEAD~2
deleted unwanted commit (carousel)
git push -f upstream RoadmapUpdate
```

**Comment by MaximMartel** [comment]
Thanks Shawn :+1:

**Pull request merged**
