### PR TITLE
New plugin: Dismissable content

### PR DESCRIPTION
**Pull request by thomasgohard**
cc/@masterbee

### CODE REVIEW

**Comment by masterbee** [comment]
@thomasgohard you have some internal linkage error on the dismissable-content pages.  
```log
dist/demos/dismissable-content/dismissable-content-en.html: internally linking to ../../docs/ref/dismissable-content/dismissable-content-en.html, which does not exist
dist/demos/dismissable-content/dismissable-content-fr.html: internally linking to ../../docs/ref/dismissable-content/dismissable-content-fr.html, which does not exist
dist/unmin/demos/dismissable-content/dismissable-content-en.html: internally linking to ../../docs/ref/dismissable-content/dismissable-content-en.html, which does not exist
dist/unmin/demos/dismissable-content/dismissable-content-fr.html: internally linking to ../../docs/ref/dismissable-content/dismissable-content-fr.html, which does not exist
rake aborted!
HTML-Proofer found 4 failures!
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/html-proofer-1.4.0/lib/html/proofer.rb:111:in `run'
/home/travis/build/wet-boew/wet-boew/Rakefile:8:in `block in <top (required)>'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

Not sure what that is since it passed out build validation.

**Comment by thomasgohard** [comment]
@masterbee Found the problem: The documentation link that's generated by the demo page template. I haven't created the documentation for the plugin yet. I'll fix that shortly and update the PR.

**Comment by thomasgohard** [comment]
@masterbee I added the documentation. That should do the trick.

I still have to add the unit testing and do some more testing of the plugin, so let me know if you find any problems and I'll fix them.

**Comment by thomasgohard** [comment]
Argh! Knew I forgot something: I didn't update the i18n. The text for the dismiss button is undefined. Getting a PR ready for that.

**Pull request merged**
