### PR TITLE
Improve ESLinting

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@nschonni

**Comment by nschonni** [comment]
Should probably use this https://github.com/jquery/eslint-config-jquery since that was the original idea I think. Although that one looks like it's missing the tab setting too.

**Comment by LaurentGoderre** [comment]
AAAAh the jQuery one works great but now there's more stuff to fix.... :(

**Comment by nschonni** [comment]
Try the `--fix` flag since there are alot of rules ESLint will fix for you

**Comment by LaurentGoderre** [comment]
@nschonni almost there but the last remaining error is scaring me...not even sure what it's supposed to be or fix it

**Comment by LaurentGoderre** [comment]
Here's the offending line https://github.com/wet-boew/wet-boew/blob/master/src/core/wb.js#L109-L110

**Comment by LaurentGoderre** [comment]
Ok, fixed it without having to risk the logic

**Comment by LaurentGoderre** [comment]
@nschonni @shawnthompson ok with merging this?

**Comment by shawnthompson** [comment]
@LaurentGoderre I'm ok with it but @nschonni is an expert.

**Review by nschonni — APPROVED** [review]
Might be a good time to rename to .eslintrc.json
Looking at some of the old overrides like `max-len` can be done later

**Comment by LaurentGoderre** [comment]
I just kept the ones that differed with jQuery

**Pull request merged**
