### PR TITLE
Carousel: Fixed various focus outline issues.

### PR DESCRIPTION
**Pull request by EricDunsworth**
* Made outlines appear around focused panel links.
* Made outlines appear around focused videos in Firefox. Might run into contrast issues against dark backgrounds.
* Carousel style 1 and 2: Fixed outline positioning issues with tab count list item in IE/Edge.
* Carousel style 1: Prevented the bottom of the tab count list item's outline from overflowing on top of panels at 200% text zoom in Firefox.
* Carousel style 2 with thumbnails: Increased visibility of outlines on focused thumbnail links.

### CODE REVIEW

**Comment by EricDunsworth** [comment]
I believe this PR is currently breaking the CSS transitions examples. I'll see if I can manage to fix it without compromising focus outlines.

**Comment by masterbee** [comment]
@EricDunsworth - thanks for this. Let us close this P.R and when you think you have the fix in place please re-P.R back.

**Comment by EricDunsworth** [comment]
@masterbee Would it be possible to re-open this PR? Once it's ready, I'll remove "[DON'T MERGE]" from its title and post a comment to state I believe it's good to go.

Pre-existing PRs can be updated/reworked without having to submit new ones.

**Comment by EricDunsworth** [comment]
@masterbee @shawnthompson @MaximMartel @LaurentGoderre @nschonni Any chance one of you could re-open this PR? I don't see any value in opening a replacement PR when I can just revise this one instead.

**Comment by EricDunsworth** [comment]
@nschonni Thanks :).

I'll try finalizing this PR later today or tomorrow.

**Comment by EricDunsworth** [comment]
Finally updated it! Should be good to go now :).

**Comment by LaurentGoderre** [comment]
@duboisp do you have time to test this?

**Comment by duboisp** [comment]
@LaurentGoderre I do not know when I will be able to test it.

**Comment by duboisp** [comment]
@LaurentGoderre I tested and it work as expected.

Thanks @EricDunsworth for fixing those focus outline issue with the carousel

**Pull request merged**
