### PR TITLE
Checkbox Filtering Bug

### PR DESCRIPTION
**Pull request by ghost**
Minor bug, rare edge case.

### CODE REVIEW

**Comment by thekodester** [comment]
I updated the PR, to prevent this or any feature edge case, the checkboxes use the own value variable, and the `$value` gets erased each time.

**Comment by duboisp** [comment]
@thekodester How I can reproduce the bug?

Here a test example where I modified the last one to reproduce the bug but without success. Are you able to provide me what test step I should follow and what I should expect working and not working? 
https://universallabs.org/wet/labs/8592-replicate-issue/unmin/demos/tables/tables-en.html

Thank you

**Comment by thekodester** [comment]
See https://github.com/wet-boew/wet-boew/issues/8559#issuecomment-468747868.

**Comment by duboisp** [comment]
Is it only a bug when the code in #8588 is added to wet-boew?

**Comment by thekodester** [comment]
No.

**Comment by duboisp** [comment]
Are you able to reproduce the bug by using the last table in this test example page: https://universallabs.org/wet/labs/8592-replicate-issue/unmin/demos/tables/tables-en.html ?

**Comment by thekodester** [comment]
It has nothing to do with the YEAR specifically...this order cause the bug:

screen shot 2019-03-07 at 1 02 50 pm

**Comment by duboisp** [comment]
Thank @thekodester 

I was able to reproduce the bug. so it is when there is "select" filter followed by a "checkbox" filter.

**Review by duboisp — APPROVED** [review]

**Pull request merged**
