### PR TITLE
Fixed various JSCS error not catched because of travis cached modules

### PR DESCRIPTION
**Pull request by LaurentGoderre**
/cc @shawnthompson

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
The build is failing because of the cached module

**Comment by masterbee** [comment]
@LaurentGoderre, you build has an error in the JSCS file. I agree with the following https://github.com/jscs-dev/node-jscs/issues/338 thread that mentions exactly the issue you have in that setting ```false``` actually trips up the rule set. It has to be set to ```null``` to be false. I did an earlier PR yesterday when I noticed the build was failing from code style issues.

Thank you for this.

**Comment by LaurentGoderre** [comment]
I wish you had read the comment......this is caused because Travis caching the modules, my PR does build when npm install is run instead of using the outdated cached modules

**Comment by andre-gh** [comment]
@LaurentGoderre I am out on the loop on this

> my PR does build when npm install is run instead of using the outdated cached modules

Do we have to wait for something to uncache?  What do you mean?

**Comment by andre-gh** [comment]
@LaurentGoderre Could you update me on what is going on with this?  Last I heard on Thursday the gcweb build was failing for odd reasons.  It looks like @masterbee tried to manually patch the lint failure out by fixing the lint issue (which just hides the problem under the rug to appear a different day).  Does this fix the issue or not?  What is the issue? Why did @masterbee close it?

**Comment by andre-gh** [comment]
@LaurentGoderre Ah, I understand now, @masterbee fixed the issue in his own PR.  What is this about cached modules though, is something else broken?

**Comment by andre-gh** [comment]
@LaurentGoderre Also, do you know why this issue suddenly came up, did jscs update?

**Comment by LaurentGoderre** [comment]
https://github.com/wet-boew/wet-boew/commit/179feecb0603b104c20685309384d766e4a3a9f8

**Comment by LaurentGoderre** [comment]
@andre-d I guess @masterbee did not read the subtext about the real issue and duplicated half of my PR to fix the apparent problem. However, the build will still fail for all developers who clone a fresh copy of the repo and do `npm install` Basically, the symptoms were fixed but not the real problem and it's going to reoccur

**Comment by andre-gh** [comment]
@LaurentGoderre Ok, but why does changing null to false fix the real issue? What is the real issue?  You didn't change anything else different.

**Comment by LaurentGoderre** [comment]
`null` doesn't do anything in grunt-jscs version 2 and high. You are all using an older version of the plugin, but the second you update, it's going to complain about 50 issues. The same problem happens with Travis. It used to do a clean install, now someone set it up to cache the node_modules that's why you have 2 different behavior on WET and on GCWeb

**Comment by andre-gh** [comment]
@LaurentGoderre Sorry for the confusion, I was not around for any of this discussion and @masterbee was misunderstanding.  Could you pull request just this one change isolated now?

**Comment by andre-gh** [comment]
@LaurentGoderre So we have to change a setting in Travis to not cache?

**Comment by LaurentGoderre** [comment]
Yep, although @nschonni might oppose to doing so

**Comment by andre-gh** [comment]
@LaurentGoderre If it is breaking the build twice somehow, there is not much justification for leaving it enabled.

**Comment by LaurentGoderre** [comment]
We could turn it on for only the bower deps since those don't change that often and don't have the same crazy nested dependencies

**Comment by andre-gh** [comment]
@LaurentGoderre We are going to disable it, its breaking too much transparently

**Comment by LaurentGoderre** [comment]
Remove this:

https://github.com/wet-boew/wet-boew/blob/master/.travis.yml#L25-L30

**Pull request closed without merging**
