### PR TITLE
Created a script to clean the wet build files

### PR DESCRIPTION
**Pull request by shawnthompson**
@nschonni what do you think? I'm always doing this on my work computer because bower keeps timing out due to slow connections.

@lucas-hay @MaximMartel @EricDunsworth

### CODE REVIEW

**Comment by nschonni** [comment]
Might be easier to add another target to [`clean`](https://github.com/wet-boew/wet-boew/blob/master/Gruntfile.coffee#L1189) since that would be more cross platform

**Comment by shawnthompson** [comment]
Can we clear the npm and bower cache with grunt?

**Comment by EricDunsworth** [comment]
@shawnthompson According to http://stackoverflow.com/questions/10456865/running-a-command-in-a-grunt-task/13186882#13186882, it could be done with either grunt-shell or grunt-exec. But that would mean adding further dependencies (although I bet those are highly unlikely to ever break)...

**Comment by shawnthompson** [comment]
Wouldn't that be an issue with cross platform also?

**Comment by shawnthompson** [comment]
@nschonni What if I put it in the `package.json` as a npm script? Would that be cross platform?

**Comment by nschonni** [comment]
If you want to do it through an NPM script, take a look at [rimraf](https://www.npmjs.com/package/rimraf) since that is what grunt-contrib-clean uses.

**Comment by LaurentGoderre** [comment]
Closing in favor of #7785

**Pull request closed without merging**
