### PR TITLE
updated imagemin to new version to fix issue with GCWeb build

### PR DESCRIPTION
**Pull request by shawnthompson**
cc/ @andre-d

### CODE REVIEW

**Comment by andre-gh** [comment]
Alright, tomorrow I will do a full out dist build and make sure we haven't broken anything with these recent dep updates.

**Comment by LaurentGoderre** [comment]
Can we just get rid of that one.....I added that module way back thinking it would be cool to keep the original in the repo and compress at build time but this module has given us so much problem. We could have a folder for source images when we want to keep non compressed source and compress the other images once and not every build.

Just a thought

**Comment by shawnthompson** [comment]
I'm ok with that

**Comment by andre-gh** [comment]
@LaurentGoderre Updating this did not even fix the issue, I am concerned there is something else wrong...any ideas why when running through grunt init it does not pick up the PNGs suddenly?

**Comment by LaurentGoderre** [comment]
Same thing as ther other issue.....the npm dependencies are being cached

**Comment by andre-gh** [comment]
@LaurentGoderre How do I fix it?  Sorry, you keep saying that but I am not understanding the implications of that.

**Comment by shawnthompson** [comment]
Can we just remove the caching option, @LaurentGoderre you said it wouldn't make that much of a difference anyways.

**Pull request merged**
