### PR TITLE
Patch: fix number range table filter when min and max are equal

### LINKED ISSUE #9235: Table filters - Number filtering issue
## Required information

**Describe the bug**
If only one value is selected when filtering by number, the search results will return the value and any value above the  selected number.

**To Reproduce**
Based on the "Number Range Filters" working example available on the WET Table Filters page: http://localhost:8000/unmin/demos/tables/tables-fltrs-en.html#dataset-filter2 use the following simplified code and try filtering using one number only. 

e.g. Enter the number 67 in the age field and the search result will return any age available from 67 and above.

```
<div class="row">
  <div class="col-md-3">
	  <h4 class="wb-inv">Filtering Options</h4>
	  <details open>
		  <summary><h4 class="h4">Filter Options</h4></summary>
		  <p class="mrgn-tp-md">Use filters to below options to change the focus of your results in following data table</p>
		  <form class="wb-tables-filter" data-bind-to="dataset-filter2">
			  <div class="form-group">
				  <fieldset>
					  <legend><span class="field-name">Age</span></legend>
					  <div class="row form-group">
						  <div class="col-md-12">
							  <label for="dt_age" class="small">Age</label>
							  <input type="number" class="form-control" id="dt_age" name="dt_age" min="0" data-column="3"/>
						  </div>
					  </div>
				  </fieldset>
			  </div>
			  <div class="form-group">
				  <button type="submit" class="btn btn-primary" aria-controls="dataset-filter2">Filter</button>
			  </div>
			  <div class="form-group">
				  <button type="reset" class="btn btn-link btn-sm p-0">Reset to defaults</button>
			  </div>
		  </form>
	  </details>
  </div>
  <div class="col-md-9">
	  <table class="wb-tables table table-striped table-hover" id="dataset-filter2" data-wb-tables='{
	  "bDeferRender": true,
	  "ajaxSource": "ajax/mockdata.json",
	  "order": [3, "desc"],
	  "columns": [
		  { "data": "id", "visible": false },
		  { "data": "first_name" },
		  { "data": "last_name" },
		  { "data": "age" },
		  { "data": "salary" },
		  { "data": "taxes" }
	  ]}'>
		  <thead>
		  <tr>
			  <th>Id</th>
			  <th>First Name</th>
			  <th>Last Name</th>
			  <th>Age</th>
			  <th>Salary</th>
			  <th>Taxes</th>
		  </tr>
		  </thead>
	  </table>
  </div>

```

**Expected behaviour**
When I enter a number in a filtering option where there is only one input field, since it's not a number range, I expect the search results to return data for that number only or zero (0) results if null.

e.g. When entering the number 67 in the date field and click the "Filter" button, the search result must return any data containing 67 only.

## Additional information (optional)

**Version of WET-BOEW/GCWeb you are using**
v4.0.44.5

**Screenshots**
table filter - number age

**Additional context**

### PR DESCRIPTION
**Pull request by radmorecameron**
## What does this pull request (PR) do?
It fixes the logic of the number range to properly handle when min and max are equal +  when there is only one number input

## Additional information (optional)
I added the tests I performed at the bottom 

**General checklist**
Make your own list for the purpose of your Pull request.

- [x] Build and test PR's code /// Rouler le script de compilation et tester le code de la PR

**Related issues**
If min and max value were the same then it would ignore the max value.
closes #9235

**Screenshots**
### Test 1
1) Don't change any values
2) All values are shown
image

### Test 2 *(this is what changed)
1) Change min and max age value to 71
2) Only see people aged 71
image

### Test 3
1) Set Min age to 71 
2) See ages for 71 and up
image

### Test 4
1) Set Max age to 50
2) Only see ages below 50
image

### Test 5
1) Set Max age to 70 and Min age to 65
2) Only see values between 65 and 70
image

### Test 6
1) Copy the table code from #9235 and replace the number filter table with the one provided in the issue description
2) Set age to 70
3) only see row of 70 year old
image

### CODE REVIEW

**Comment by duboisp** [comment]
Pre-approved upon successful testing and code review. @polmih please create working example as needed to fully test it.

**Review by polmih — CHANGES_REQUESTED** [review]
Test 1- 5 works as expected (tested on localhost)
Test Nr.6 should have the same behavior as Test Nr.3 

- [x]  The test without a Max input field the default max value should be infinite

**Comment by polmih** [comment]
@radmorecameron , if you have some time you can join us at our [WET Office Hours afternoon session](https://github.com/wet-boew/wet-boew/wiki/WET-Office-hours,-Heures-de-service-de-la-BOEW) to fix this issue faster.

**Comment by radmorecameron** [comment]
> Test Nr.6 should have the same behavior as Test Nr.3
> 
> * [ ]   The test without a Max input field the default max value should be infinite

Ahh, I didn't realize that was the intended functionality. Does that mean #9235 should be closed as invalid?

**Comment by polmih** [comment]
> > Test Nr.6 should have the same behavior as Test Nr.3
> > 
> > * [ ]    The test without a Max input field the default max value should be infinite
> 
> Ahh, I didn't realize that was the intended functionality. Does that mean #9235 should be closed as invalid?

Ooh, in this case your solution should work, you just need to adjust the Test Nr. 6 (with one field) where the field is waiting for an unique value and not a MIN value. Thank you! :)

**Comment by radmorecameron** [comment]
> > > Test Nr.6 should have the same behavior as Test Nr.3
> > > 
> > > * [ ]     The test without a Max input field the default max value should be infinite
> > 
> > 
> > Ahh, I didn't realize that was the intended functionality. Does that mean #9235 should be closed as invalid?
> 
> Ooh, in this case your solution should work, you just need to adjust the Test Nr. 6 (with one field) where the field is waiting for an unique value and not a MIN value. Thank you! :)

Sorry about that, the test has been updated.

**Comment by polmih** [comment]
> > > > Test Nr.6 should have the same behavior as Test Nr.3
> > > > 
> > > > * [ ]      The test without a Max input field the default max value should be infinite
> > > 
> > > 
> > > Ahh, I didn't realize that was the intended functionality. Does that mean #9235 should be closed as invalid?
> > 
> > 
> > Ooh, in this case your solution should work, you just need to adjust the Test Nr. 6 (with one field) where the field is waiting for an unique value and not a MIN value. Thank you! :)
> 
> Sorry about that, the test has been updated.

No worries, it's great job :) . The only thing missing is an example for your Test Nr.6. 
Would it be possible to add that case on the example pages: 

- https://wet-boew.github.io/wet-boew/demos/tables/tables-fltrs-en.html
- https://wet-boew.github.io/wet-boew/demos/tables/tables-fltrs-fr.html

Thank you @radmorecameron

**Comment by radmorecameron** [comment]
@polmih I have added an example table (number inputs = exact match, text input = field contains the value)
image

**Review by polmih — APPROVED** [review]
Tested locally, works as expected

**Review by polmih — APPROVED** [review]

**Comment by polmih** [comment]
> 

Done. Thanks

**Pull request merged**
