### PR TITLE
menu - Bug fix for issue #8361

### LINKED ISSUE #8361: accessibility issue with wetboew library, empty a tags generated by wetboew js library, fails WCAG2AA
WCAG 2AA issue, empty a tags.

details in this thread:
https://www.drupal.org/project/wetkit/issues/2947343

I have isolated the issue to the wetboew js library code, the wetboew library incorrectly adds empty a tags into menu items under certain circumstances.
see screenshot:
https://www.drupal.org/files/issues/screenshot_mb-item_WCAG2AA-wet-boew.png

easy steps to reproduce: 
https://www.drupal.org/project/wetkit/issues/2947343#comment-12510758

some pretty bizarre behaviour from the wetboew library js code.

I looked through these queues here and found nothing related.

To detect these errors, use the WPSS scanning utility OR something like the docker image, the-a11ym-machine which reports WCAG2AA compliance.

### PR DESCRIPTION
**Pull request by zzucco**
Fix for creation of faulty mobile panel menu items under certain conditions.

This will not work if there are multiple links in the same grid cell, but I don't think that should ever happen since you would use a list in that scenario.

Fixes #8361

### CODE REVIEW

**Comment by zzucco** [comment]
TO DO:
Test for heading followed by list (see https://goo.gl/UoJwA5)

**Comment by duboisp** [comment]
FYI - @zzucco is working on improving the documentation. That new docs will be added to this PR. It will include more information about what the design pattern should be followed and what the design pattern should be avoided.

**Comment by zzucco** [comment]
Since this PR has been pretty stale, here's an update.
The update to the documentation has been ready for a little while, but since I don't have git or any other tools on my machine, it's quite a hassle to add them to the PR. I've been working on it bit by bit.

My recommendation is that we go ahead with merging the bug fix, and the docs would be updated at a later date.

**Comment by duboisp** [comment]
@zzucco thanks, but we will wait for the docs before to merge this PR. 
I will work with you in the coming weeks to publish your work on github.

Thanks

**Comment by duboisp** [comment]
@zzucco do you have a time estimate when this could be completed?

**Comment by duboisp** [comment]
@zzucco as discussed, I create a build here: http://universallabs.org/wet/labs/pr-8394/index-en.html

**Comment by duboisp** [comment]
I will rebuild it and do some test

**Comment by zzucco** [comment]
I am now able to build WET myself, so I can run my own tests.
The docs are currently not functioning properly.

**Comment by zzucco** [comment]
I'm fairly certain this last version is good enough. 

This patch not only adds the documentation, it also adds some functionality for pages. You can now AJAX in a footer, like we can do with the menu. You can also group example pages under a single parent page. Both of these are used in the new working examples.

There is one issue with the pages. When a footer is AJAX'd in, the menu panel will not render it. This is because the menu panel is created before the footer is AJAX'd. In my opinion, this is a very minor issue not worth fixing. If we really wanted it to work properly, the best way would be to manually add the footer after the pages have been built. Otherwise, we would have to make significant changes to the menu source code.

**Comment by duboisp** [comment]
I will re-build and post the link for review

**Comment by duboisp** [comment]
Here a build with the latest changes: http://universallabs.org/wet/labs/pr-8394/index-en.html

**Review by duboisp — DISMISSED** [review]

**Review by duboisp — APPROVED** [review]

**Comment by duboisp** [comment]
@zzucco can you squash your commits? Once it's done I am going to merge your PR.

**Pull request merged**
