### PR TITLE
Calendar of events: fix #7609 and improved how the focus is determined

### LINKED ISSUE #7609: Calendar of Events: Multiday event as first or only event in the calendar
There is an issue with the calendar of events if your first event (or only event) is a multiple day event.

The calendar renders like this:

screen shot 2016-07-15 at 9 03 50 am

I created a working example of the problem.

https://shawnthompson.github.io/wet-boew-calendar/demos/cal-events/cal-events-en.html

@masterbee

### PR DESCRIPTION
**Pull request by duboisp**

### CODE REVIEW

**Comment by shawnthompson** [comment]
What no new branch? 😺 
Thanks for doing this... I'm checking it now.

**Comment by shawnthompson** [comment]
Works! Thanks!
@MaximMartel @lucas-hay @masterbee

**Comment by LaurentGoderre** [comment]
:-1: this pr needs to be cleaned up. Too much dom manipulation and there's code duplication. Wish I had created unit tests for this plugin

**Comment by cwhyman** [comment]
Hello, i am having the same issue as #7609 i've seen on the original thread that the issue was closed and a push was done for a fix, I have tested out the pushed code and it seems as though the push has removed the functionality of multi day events, if this is not the case is there a different way to define a multi day event that I am unaware of.

Thanks.

**Comment by duboisp** [comment]
@cwhyman Please create a [new issue ](https://github.com/wet-boew/wet-boew/issues/new) with your question/issues.

**Comment by cwhyman** [comment]
@duboisp my question is more to do with the code that was changed with the fix you published, did you remove the ability for multi day events? if I still need to create a new question/issue I will but I thought I would come to the commit that changed the code.

**Comment by duboisp** [comment]
@cwhyman Yes it is preferable to create a new issue and then add a reference to this PR. I will be more than welcome to answer at your question. This PR are closed so any conversation may go unnoticed by the wet-boew community.

Cheers

**Pull request merged**
