### PR TITLE
To details-summary, add the ability to have it collapsed in mobile an…

### PR DESCRIPTION
**Pull request by jilusan**
…d expended in desktop.

### CODE REVIEW

**Comment by nschonni** [comment]
The behaviour of a polyfill should match the native verion. I think you want to look at the expand/collapse plugin instead

**Comment by jilusan** [comment]
@shawnthompson  What do you think?

**Comment by shawnthompson** [comment]
@nschonni We have an expand and collapse plugin? I always thought that's what detail/summary was? That's what people are using it for. The title for this polyfill is "[Details/summary polyfill (**expandable/collapsible content**)](http://wet-boew.github.io/v4.0-ci/unmin/demos/details/details-en.html)"

**Comment by nschonni** [comment]
Sorry, I meant [toggle](https://wet-boew.github.io/v4.0-ci/unmin/demos/toggle/toggle-en.html)

**Comment by LaurentGoderre** [comment]
:+1: on using toggle for this. Polyfill should match the native implementation

**Comment by LaurentGoderre** [comment]
Speaking of which, the details summary doesn't right now I think. The way to open and close them is different on native and non native, we should fix that

**Comment by shawnthompson** [comment]
@LaurentGoderre @nschonni, if we do move this functionality to the toggle plugin, should we just kill this branch and PR and start from scratch?

**Comment by LaurentGoderre** [comment]
either way, update the pr or create a new one

**Comment by masterbee** [comment]
@jilusan and @shawnthompson - lets close this P.R and create a new one. It will be a bit cleaner for notes and comments since I think it will lead to a healthy discussion.

**Pull request closed without merging**
