### PR TITLE
Details/Summary: Fixed the double description in the french demo that crashes the build

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by andre-gh** [comment]
Why did this just start crashing now?

**Comment by LaurentGoderre** [comment]
Because a nested dependency of assemble was updated and probably started doing more through front-matter validation

**Comment by andre-gh** [comment]
Right, that happens a lot

**Comment by LaurentGoderre** [comment]
Weclome to dependency management.....the opposite problem is still way worse

**Pull request merged**
