### PR TITLE
DataTable: Edge Case (Removal)

### PR DESCRIPTION
**Pull request by ghost**
Please see: https://github.com/wet-boew/wet-boew/issues/7825

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Haven't tested it but I agree in principle!

**Comment by shawnthompson** [comment]
#7937 has been merged, can you rebase and retest your change?

**Comment by kodecount** [comment]
All updated.

**Review by lucas-hay — APPROVED** [review]
Approved at PR review meeting.

**Pull request merged**
