### PR TITLE
Build: Remove SauceLabs leftovers

### PR DESCRIPTION
**Pull request by EricDunsworth**
Removes the following:
* "saucelabs" and "saucelabs-mocha" grunt tasks
* Mention of SauceLabs in the "test" task's description
* SauceLabs reference from readme
* grunt-saucelabs dependency
* "SAUCE\\|" from grep command in .travis.yml

SauceLabs was disabled in #8031.

### CODE REVIEW

**Comment by EricDunsworth** [comment]
@duboisp @GormFrank @LaurentGoderre @nschonni Any thoughts on this?

The way I see it, there are 3 choices to sort this out:
1. Keep the status quo (not ideal)
2. Remove what's left of SauceLabs in wet-boew given that it hasn't been used for 2+ years (i.e. what this PR does)
3. Bring SauceLabs testing back to life

**Comment by nschonni** [comment]
I believe it was disabled because of PR failures related to timeouts that can happen running the tests.
The other option to getting it back into the pipeline without slowing down PRs, would be to move it to something that only runs when things are actually merged into master.

**Comment by GormFrank** [comment]
@duboisp We have to look into this.

**Comment by EricDunsworth** [comment]
@GormFrank @duboisp Any updates on this?

**Review by GormFrank — APPROVED** [review]

**Comment by GormFrank** [comment]
We can get rid of it, and at some point if we want it back we could just look at the GitHub history. It is better not to have it then show Unknown. This PR has waited for more than a year now.

**Comment by GormFrank** [comment]
Approved during technical review upon testing.

**Review by GormFrank — APPROVED** [review]

**Pull request merged**
