### PR TITLE
removed italics in required class to help with accessibility

### PR DESCRIPTION
**Pull request by shawnthompson**
cc/ @masterbee @pjackson28

### CODE REVIEW

**Comment by ciclerou** [comment]
When will this go to production?

**Comment by LaurentGoderre** [comment]
V4.0.21 was just release and should contain these changes

**Comment by ciclerou** [comment]
I don't see it on the CDN site...it only has up to v4_0_20 ?
https://ssl-templates.services.gc.ca/app/cls/wet/gcweb/

**Comment by rlambert27** [comment]
Hello,

The CDTS (formerly CDN) must create a build using the new version. It takes us approx. 2-3 weeks before release a new version with the v4.0.21 build. If you are registered on GCPedia you will be notified as soon as the new version is released.

**Comment by ciclerou** [comment]
Could you  please provide link for this gcpedia page so I can join?

**Comment by rlambert27** [comment]
Sure, all the information concerning the CDTS is here : 

http://www.gcpedia.gc.ca/wiki/Centrally_Deployed_Templates_Solution_%28CDTS%29

The registration page is here:

http://www.gcpedia.gc.ca/wiki/Centrally_Deployed_Templates_Solution_%28CDTS%29/Registration

**Comment by ciclerou** [comment]
I added both of these pages as my favorites, but on the registration page, it only shows users in a list and I don't see where I can add my name.  Am I missing something?  (I only see Mario's name)
cdts

**Comment by ciclerou** [comment]
ok thanks...took me a while, but I figured it out :+1:

**Pull request merged**
