### PR TITLE
change `gc-elps` to `wb-elps` to use WET namespace

### PR DESCRIPTION
**Pull request by shawnthompson**

### CODE REVIEW

**Comment by shawnthompson** [comment]
@neoinsight @coprisanu this is / was being used for the new search styles.

**Comment by duboisp** [comment]
@shawnthompson what that style do? I am not able to find any reference in our [style guide](http://wet-boew.github.io/wet-boew-styleguide/v4/index-en.html)?

**Comment by shawnthompson** [comment]
@duboisp it's not in the style guide. I asked @cfarquharson to add it. That's when we noticed it was using the wrong namespace. 

It adds ellipses / truncates the text to the width of the containing element.

**Comment by duboisp** [comment]
Thanks  @shawnthompson :-)

**Pull request merged**
