### PR TITLE
Navcurrent - fixing #7643

### PR DESCRIPTION
**Pull request by shawnthompson**
@kodecount @duboisp 

Let me know if this is all that needs to be done.

Thanks

### CODE REVIEW

**Comment by duboisp** [comment]
@shawnthompson have you try to git cherry pick @kodecount [commit](https://github.com/kodecount/wet-boew/commit/72df780dcf7426257751698c2b1dc4665bb1dbae) instead of copying it?
Prior to cherry pick you will need to add his repo into your local remote (```git add remote RemoteName RemoteURL```) then fetch it and then you should be able to cherry pick

Let me know if you have question

:-)

**Comment by shawnthompson** [comment]
@duboisp Like this?

**Comment by duboisp** [comment]
@shawnthompson  Yes

**Comment by duboisp** [comment]
I successfully reproduced the bug, and I confirm this PR fix it.

**Comment by LaurentGoderre** [comment]
It would be nice to do unit tests instead of manual tests for stuff like this

**Comment by duboisp** [comment]
For this particular issue, it could be difficult because I was able to reproduce the issue by looking at
http://wet-boew.github.io/v4.0-ci/demos/index-en.html compare to http://wet-boew.github.io/v4.0-ci/demos/tables/tables-en.html

but I was unable to reproduce by using this domain
http://wet-boew.github.io/wet-boew/demos/index-en.html compared to http://wet-boew.github.io/wet-boew/demos/tables/tables-en.html

so I manually modified the ajaxed menu in order to reproduce it locally.

But @LaurentGoderre I agree with you that simple thing should have a unit test for.

**Comment by kodecount** [comment]
We actually got a complaint about this during testing of new application multiple users were confused on how to get back to previous page (menu has one link, but it was dark blue as previous page (even though it a sub page of previous page)). We won't see this fix until the next stable version of WET but it goes to show that such small issue could easily confuse people.

**Pull request merged**
