### PR TITLE
CSS: Enable styling legends for checkbox and radio button groups as labels.

### LINKED ISSUE #5797: Incorrect font sizes are applied to Form Validation Examples for Fav Pets and Citizenship Status
Incorrect font sizes are applied to Form Validation Examples for Fav Pets and Citizenship Status

http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html#lname1

Assuming the correct size:
screen shot 2014-07-25 at 2 58 44 pm

And the incorrect size:
screen shot 2014-07-25 at 2 58 38 pm

### PR DESCRIPTION
**Pull request by thomasgohard**
Fixes #5797.

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
To fix the build:

```css
fieldset {
	border-top: 1px solid $legend-border-color;
	padding-top: 10px;

	&:first-child {
		border-top: 0;
	}


	/*
 	*	Fieldset/legend as a label for a group of checkboxes or radio buttons
 	*	https://github.com/wet-boew/wet-boew/issues/5797
 	*/
	&.chkbxrdio-grp {
		border-top: 0;
		padding-top: 0;

		legend {
			font-size: $font-size-base;
			font-weight: bold;
			margin-bottom: 5px;
		}
	}
}
```

**Comment by LaurentGoderre** [comment]
Is this a new class you are introducing or you adding something new?

**Comment by LaurentGoderre** [comment]
Please fix the merge conflicts

**Comment by andre-gh** [comment]
Can this pull request be closed, has it gone stale?

**Comment by andre-gh** [comment]
@thomasgohard Since this fixes an issue, are you willing to resume this pull request or should I take it over?

**Comment by thomasgohard** [comment]
@andre-gh I've rebased this PR. It's ready for review and merging.

**Comment by andre-gh** [comment]
Thanks, I should remember to update the docs/demo later.

**Pull request merged**
