### PR TITLE
Base: add color variable in top instead of using color code

### PR DESCRIPTION
**Pull request by nongpp**
add color variable in top instead of using color code

### CODE REVIEW

**Comment by lucas-hay** [comment]
@nongpp We will be happy to merge this, but could you please update your commit message. (The description you have in the commit description would suffice). see below:
"Base: add color variable in top instead of using color code"

**Comment by LaurentGoderre** [comment]
I think variable should be descriptive of their purpose and not the color themselves

**Comment by EricDunsworth** [comment]
In addition to what @LaurentGoderre said, I'd recommend making the following changes:

1. Move the SCSS variable declarations into [wet-boew/theme/_variables.scss](https://github.com/wet-boew/wet-boew/blob/master/theme/_variables.scss).
2. Refine the comments before the variable declarations to be more in line with what's already done in [wet-boew/theme/_variables.scss](https://github.com/wet-boew/wet-boew/blob/master/theme/_variables.scss).
3. Revise the commit's description to be shorter/more meaningful and prefix it with the commit's topic. I'd recommend going from this:

> Update _base.scss
>
> add color variable in top instead of using color code

To something along these lines:

> Theme: add color variable in top instead of using color code

**Comment by nongpp** [comment]
@lucas-hay Thank you for your respond. And is it ok if I correct all css like this or I set every variable into  wet-boew/theme/_variables.scss.?

**Comment by lucas-hay** [comment]
@nongpp If you wish to add more varaibles, that would be great. Just follow what @EricDunsworth and @LaurentGoderre have mentioned. (use _variables.scss, more descriptive name, comments above, etc.)

**Comment by nongpp** [comment]
@lucas-hay @LaurentGoderre @EricDunsworth thank you for your advice. I will follow your advice.

**Comment by lucas-hay** [comment]
@nongpp should we close this PR? 
It appears you moved this into #8199

**Pull request closed without merging**
