### PR TITLE
DataTable Filtering With Checkboxes

### PR DESCRIPTION
**Pull request by ghost**
For #8546...Allows the filtering with checkboxes using data-tables regex search.

### CODE REVIEW

**Comment by thekodester** [comment]
See live demo here: https://www.thekodester.ca/wet/tables/dtfiltering

**Comment by michael-milette** [comment]
@thekodester 

Definitely a +1 from me.

This is great!!! Thank you!

Michael

**Comment by duboisp** [comment]
Thanks @thekodester for your contribution

We would need a E&F working example and the documentation before to merge this.

**Comment by thekodester** [comment]
Did you want me to change the current example to include checkboxes for one of the dropdowns?

**Comment by thekodester** [comment]
I added the update to the example pages.

**Review by duboisp — CHANGES_REQUESTED** [review]
The "clear" don't work properly for checkboxes, you might need to add one JS line here: https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tables/tables.js#L206

**Comment by michael-milette** [comment]
Hi @thekodester,

I would like to try this out with our application. It looks like everything was finished about 10 days ago. Where can I get access to the documentation and final code? I am very excited to give it a try.

Best regards,

Michael

**Comment by thekodester** [comment]
Hey @michael-milette,

Once this gets the final approval from @duboisp it should be merged and available when 4.0.30 come out that the hope anyways.

Thanks,

Kody

**Review by duboisp — APPROVED** [review]

**Comment by michael-milette** [comment]
Thank you @duboisp and @thekodester,

It works great! I already have it setup with one of our datatables. Any chance it can be integrated into https://github.com/wet-boew/themes-dist.git soon?

Best regards,

Michael

**Comment by duboisp** [comment]
@michael-milette you means when it will be included in the release of gcweb? I am currently working on that and it will be included in gcweb v5. 

An alternative if you need that fix asap in your gcweb theme implementation, you can simply replace the wet-boew.js file. You can follow the same process as to apply the [v4.0.29.1 patch](https://wet-boew.github.io/wet-boew/docs/versions/v4.0/patch-for-v4.0.21-to-v4.0.29-en.html)

**Comment by michael-milette** [comment]
Thanks @duboisp

**Comment by michael-milette** [comment]
Hi @thekodester ,

We did a little more extensive testing today and I believe we found a bug.

# Description

I have a datatable with two fields: Pillars and Provinces. Checking a box in the first field and none in the second field produces 0 results.

# How to Reproduce the issue

Create a form similar to your working example but with two fields. Both fields should be check boxes. The first will be Pillars and the second Provinces in this example.

- Test 1: Checking boxes in both fields - Success. Produces the expected results.
- Test 2: Checking a box ONLY in the first (Pillars) field - Failure. Produces 0 results.
- Test 3: Checking a box ONLY in the second field - Success. Produces the expected results.
- Test 4: Reverse the order of the fields by physically swapping the order of the HTML: Provinces first, Pillars second. Repeat Test 2. Same results except that, this time, it is still the first field (Provinces) field that fails - produces 0 results.

# What was Expected

Regardless of the order in which the fields appear, behavior should be consistent between the first and second field.  Checking one or more of the checkbox filters in the first field without any in the second should not result in 0 results.

Let me know if you have any questions. I can make a working example available upon request.

Best regards,

Michael

**Comment by thekodester** [comment]
I post your own issue with a working example (or some code your using) as the example on my site has no issues.

**Comment by duboisp** [comment]
@michael-milette Thanks for finding that bug, please open a new issue. 
Any fix for that issue should be submitted via a new pull request.

**Pull request merged**
