### PR TITLE
Multimedia player: Fixed linking issues in video demos.

### PR DESCRIPTION
**Pull request by EricDunsworth**
* Updated broken transcript links to point to wet-boew's pre-existing transcript pages.
* Restored missing poster images.
* Created a new poster image for the French version of the second video, based on a screenshot. Its original poster image was wrong (copy of the first video's image).
* Updated broken "Share this video" URLs.
* Partially addresses #7861.

### CODE REVIEW

**Comment by EricDunsworth** [comment]
@duboisp FYI.

**Comment by EricDunsworth** [comment]
Btw I was originally planning on porting the Service Canada site's decommissioned transcript pages (with a few adjustments) into wet-boew, but at some point I noticed that transcript pages already existed in the repo. The only issue was that nothing linked to them...

I should note that the original Service Canada transcript pages contained media players prior to their "Transcript" sections. I didn't see much value in retrofitting the players into the pre-existing transcript pages.

**Comment by LaurentGoderre** [comment]
All good!

**Comment by duboisp** [comment]
Thanks @EricDunsworth & @LaurentGoderre

**Pull request merged**
