### PR TITLE
Added a docker build environemnt

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
PhantomJS pre-compiled phantomjs doesn't seem to like phantomJS so it probably need to be added to the docker image. ALso need to figure out the issue with ruby install and proxy

**Comment by sylus** [comment]
Your likely blocked on this:

https://github.com/ariya/phantomjs/issues/14186

More specifically:

https://github.com/ncopa/docker-phantomjs-alpine/issues/2

Hopefuly ncopa can get a fix for this soon.

For right now you can cheat by: https://github.com/drupalwxt/gitlab-ci/blob/master/Dockerfile#L16

I will see if I can direct ping ncopa to take a look at this, since a lot of users want phantomjs to work with alpine. The strace command points to `pselect6` being the problem.

**Comment by duboisp** [comment]
I know this is still a work in progress, but I assume that some documentation will be included in this PR on how to use the docker.

**Comment by LaurentGoderre** [comment]
@duboisp Yeah though there won't be much.... you just run `source script/docker/activate` and everything after that all the  npm, grunt and bower command are routed to the docker container. To leave the dockerize environment, you run the deactivate command

**Comment by duboisp** [comment]
@LaurentGoderre thanks. 

Can I assume you will add that info somewhere in the [wet-boew documentation](http://wet-boew.github.io/wet-boew/docs/index-en.html)?

**Review by lucas-hay — APPROVED** [review]
Approved at PR review meeting.

**Pull request merged**
