### PR TITLE
Auto add close button to overlays

### PR DESCRIPTION
**Pull request by ghost**
Related:
- https://github.com/wet-boew/GCWeb/issues/1156
- https://github.com/wet-boew/wet-boew/pull/7908

### CODE REVIEW

**Comment by kodecount** [comment]
See a demo: https://kodecount.ca/demos/overlays/

**Comment by shawnthompson** [comment]
https://shawnthompson.github.io/kodecount-overlay-close/unmin/demos/overlay/overlay-en.html

**Review by lucas-hay — APPROVED** [review]
Tested with link posted in PR from @shawnthompson in PR review meeting. Approved at PR review meeting.

**Comment by kodecount** [comment]
Since were adding ability to change light-box buttons should these have the same thing?

**Pull request merged**
