### PR TITLE
Navcurrent: breadcrumb issue

### LINKED ISSUE #7643: Problem with the left menu. Version:  GoC.WebTemplate 4.0.21.2
The second level of the left menu is showing "Selected" for more than one file.

It should be associated only with the file "Documents.aspx" but it is also "selected" when displaying the file "DocumentsUpload.aspx".

Here is the code that I am using to generate the left menu in both pages:

``` vb
Dim oMenuSection As MenuSection = New MenuSection()

' Level 1
oMenuSection.Name = "Financial Transaction"
oMenuSection.Link = "FinancialTransaction.aspx"

' Level 2
oMenuSection.Items.Add(New MenuItem("ReviewersSignatories.aspx", "Reviewers and Signatories"))
oMenuSection.Items.Add(New MenuItem("Documents.aspx", "Supporting Documents"))
oMenuSection.Items.Add(New MenuItem("HistoricalVersions.aspx", "Historical Versions"))

' Add Menu Section
Page.WebTemplateMaster.WebTemplateCore.LeftMenuItems.Add(oMenuSection)
```

FYI, When removing the breadcrumbs in both pages, this problem disappear.

Thank you

file_1
file_2

### PR DESCRIPTION
**Pull request by kodecount**
Navcurrent reads the entire breadcrumb which results in false postive. Fixes #7643.

### CODE REVIEW

**Comment by kodecount** [comment]
@shawnthompson @masterbee When could this be merged would it be in the next release?

**Comment by kodecount** [comment]
@MaximMartel @masterbee @shawnthompson When could this be merged and would it be in the next release?

**Comment by shawnthompson** [comment]
@kodecount, You will need to squash your commits.

**Comment by kodecount** [comment]
@shawnthompson How do I do that? New to all of this.

**Comment by shawnthompson** [comment]
@kodecount here's a link to a resource.

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

Normally when you fix a commit you can just amend it instead of adding a new commit. You would have to `add` your new change to staging and then amend your commit with the following command.

```
git commit --amend
```

If this opens in _vi_ you just need to write the file and quit _vi_ by typing the following.

```
:wq
```

This will redo the commit with your changes. If you already pushed your commit to Github, you need to _force push_ your amended commit back up to your _origin_, with the following command.

```
git push -f origin BRANCH_NAME
```

Where _BRANCH_NAME_ is the name of the branch your work is on.

Even if you started a PR, your new change will be applied and Travis will restart your verification build.

**Comment by shawnthompson** [comment]
@LaurentGoderre, @duboisp Can you verify @kodecount's change?

**Pull request closed without merging**
