### PR TITLE
Build: Fixed CSS/image references on minified pages.

### LINKED ISSUE #6865: Missing theme.min.css on Key Resources pages
Any page linked under the "Key Resources" section of the start page (http://wet-boew.github.io/v4.0-ci/index-en.html) is showing a 404 on the theme.min.js file.  Looks like it's going up one directory too high?

### PR DESCRIPTION
**Pull request by EricDunsworth**
Fixes #6865.

### CODE REVIEW

**Comment by EricDunsworth** [comment]
This fixes the theme CSS/image references on the unminified and minified versions of all the docs/demo/etc pages... but it's currently breaking those references in unminified theme pages.

**Comment by EricDunsworth** [comment]
Now it should be good to go :)!

@thomasgohard @LaurentGoderre If the automated build passes, any chance this could be merged in ASAP? All the minified demo/docs/etc pages currently look like walls of text... this PR fixes it :).

**Comment by EricDunsworth** [comment]
I don't know why Travis-CI is still failing at this point :(. Even on my up-to-date master branch (without this PR's change) I keep running into PhantomJS errors with ``grunt pre-mocha`` and ``grunt mocha``.

**Comment by LaurentGoderre** [comment]
It seemed like an issue with a 3rd parties. In any case that fix was not sufficient to fix the problem and my latest PR is fixing this problem

**Pull request closed without merging**
