### PR TITLE
Build: Updated minimum time-grunt version to 1.3.0.

### PR DESCRIPTION
**Pull request by EricDunsworth**
Should prevent random invalid array length errors from appearing when it calculates bar lengths.

### CODE REVIEW

**Comment by EricDunsworth** [comment]
Just to give more context...

Last week I did a fresh install of node.js 0.12.10 and ran ``script\setup``, but time-grunt failed at the very end. WET's build system currently uses  time-grunt 1.0.0.

I tried reproducing the error by clearing my npm/bower caches, removing my lib/node_modules folders and re-running ``script\setup``. All of those attempts succeeded. So I guess the error is kind of random. Anyway, the same error was reported in sindresorhus/time-grunt#58 and subsequently resolved in time-grunt 1.1.1.

Since time-grunt 1.0.0 is ancient history and 1.1.1 is nearly a year old by now, I figured there'd be value in moving right over to 1.3.0. I installed it and tried a few tests with ``script\setup`` and ``grunt``. Didn't run into any issues.

**Screenshot of error in time-grunt 1.0.0:**
time-grunt

**Screenshot of same point in time with time-grunt 1.3.0:**
time-grunt_fixed1 3 0

**Comment by EricDunsworth** [comment]
@masterbee @shawnthompson @LaurentGoderre Assuming none of you have any concerns, is there any chance this, #7421 and #7476 could be merged in before v4.0.22 gets released? I'm kind of surprised they didn't make it into 4.0.21 (since they were sent throughout February/March). Thanks :).

**Comment by shawnthompson** [comment]
I'll merge this one and look into the other ones next

**Comment by EricDunsworth** [comment]
@shawnthompson Thanks :)!

**Pull request merged**
