### PR TITLE
Plugin Menu: replaces Javascript setTimeout to a css delay

### PR DESCRIPTION
**Pull request by stevenbriscoeca**
So this is my first commit to get my feet WET.

I made the menu have a delay without JavaScript by only using css delays. I also made it that the submenu styles are there by default and not just when you add the class `.sm.open`.

Now I am fully aware that menus are complex. This pullrequest is just to see you guys thoughts on the modification. If you like it, great! If you don't, no worries, I will work on something else WET related or update the pull request if you like the direction.

Let me know your thoughts.

Stephen

### CODE REVIEW

**Comment by nschonni** [comment]
[`transition-property`](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-property) appears to be IE10+ so it wouldn't meet the current(?) support for IE8+

**Comment by stephenbe** [comment]
hmm good point. I thought you guys didn't support IE8 anymore.

http://wet-boew.github.io/wet-boew/docs/versions/rdmp-en.html

Summer/Fall 2014	End of support for IE8 (when IE8 usage is below 5%)

Even then, for this pr to pass, it would have to degrade gracefully for IE9...

Still was a fun mini project to do and to learn wet!

**Comment by shawnthompson** [comment]
Welcome to the beautiful world of WET @stephenbe!

**Comment by stephenbe** [comment]
Thank you Shawn! I have so much to learn!

**Comment by pjackson28** [comment]
Technically IE8 and IE9 are outside of the support window, as they are both below 5%, but we should still be careful to avoid removing existing support.

It is an interesting idea to use CSS for this purpose (and good to minimize the use of JS where possible), but was the resulting behaviour the same as with JS? I seem to recall someone trying a CSS-based approach before but there were some behavioural differences in comparison to the JS-based approach.

**Comment by stephenbe** [comment]
I did compare my working copy to the menu on http://wet-boew.github.io/wet-boew/docs/ref/wetsites-en.html and I made sure that there is 0 difference! 

Good to know about IE8, IE9!

**Comment by pjackson28** [comment]
That's good. I think the behaviours where there previously was difficulty involved moving off and back on an item or transitioning between items where there was a change in the delay. So for instance moving the mouse pointer from a menubar item towards the submenu but briefly going over the next item on the way to the submenu. Same with moving off a menu item and back on. So there was 0 differences in those scenarios as well?

**Comment by stephenbe** [comment]
Alright i'll test that out and get back to you before tomorrow morning. It should be fine because I kept the classes.

I will let you know for sure.

**Comment by stephenbe** [comment]
wet

Here you can my fork and how it interacts...you can use this to compare with the live version. The only difference I see is when you hover fast on all the menus, you the gray backgrounds has a small delay before being removed. Other then that, pretty much the same!

@pjackson28

**Comment by LaurentGoderre** [comment]
Can you rebase your branch to clean it up?

**Comment by LaurentGoderre** [comment]
BTW, how did you do that screencast?

**Comment by stephenbe** [comment]
Hello @LaurentGoderre,

For the rebase, do you mean that everything should be up to date? I updates last night with all the last updates and resolved a conflict, you can see this here : https://github.com/stephenbe/wet-boew/commit/5764156ddb7b1d62b8e13f68942abba3a90d1eab. Consequently, everything should be up to date and ready to merge.

I used http://www.cockos.com/licecap/ to record my demo.

Thank you!

**Comment by pjackson28** [comment]
@stephenbe So what would be the end result on IE8 and IE9? Do the menus still show up? What would be missing should this change be implemented? They technically may not be supported any more but we should be mindful of the impact on those browsers.

**Comment by LaurentGoderre** [comment]
@stephenbe the rebase is to get rid of these merge commits. if you do

```
git fetch upstream,
git rebase upstream/master
git push -f mybranch
```

**Comment by stephenbe** [comment]
By doing a rebase I needed to delete my master branch so it doesn't recreate a merge 

I made a new one here : 

https://github.com/wet-boew/wet-boew/pull/6806

Sorry about that, I'm still learning git!

**Comment by LaurentGoderre** [comment]
You didn't need to delete the branch to rebase. Next time this happens, let's work on updating the existing pr because it's a very important step for contributing to other projects as well

**Comment by stephenbe** [comment]
I understand, I'm very sorry this happened, I thought that I would be able to reopen the issue once I re-added my branch. Next time I will start by rebasing and create a separate branch just for my update.
 Thank you for understanding, I will make sure this doesn't happen again for my next PR on WET.

**Comment by LaurentGoderre** [comment]
hey don't worry about it!! I just want to help you learn this stuff

**Comment by stephenbe** [comment]
Thank you so much! I really really appreciate it! At my work, we use SVN so it's a tad different then git! We are slowly starting to merge everything to git, so I still have a lot to learn. To squash all the commits into one with a rebase, I might need your help for that though, i'm trying to search a solution and I'm not finding any definite answers. I will keep searching for answers tonight!

**Comment by LaurentGoderre** [comment]
Use the folloowing command:

```
git rebase -i HEAD~5
```

where -i mean interactive and HEAD~5 means 5 version behind your current commit. It will launch vi witch instructions on how to do it

**Pull request closed without merging**
