### PR TITLE
Update wetsites-fr.hbs

### PR DESCRIPTION
**Pull request by peterparkers**
change from http to https for website that supported https
(for French language site)

### CODE REVIEW

**Review by duboisp — CHANGES_REQUESTED** [review]
See my comment in https://github.com/wet-boew/wet-boew/pull/8222#pullrequestreview-80886836 and make the similar adjustment for link here.

**Comment by duboisp** [comment]
@peterparkers BTW - Thanks for your contribution

**Comment by duboisp** [comment]
@peterparkers Can I assume this PR is superseeded by #8225?

**Comment by peterparkers** [comment]
@duboisp yes

**Pull request closed without merging**
