### PR TITLE
Calendar - Show today date or the closest on initialization

### PR DESCRIPTION
**Pull request by duboisp**
Alternate solution of PR #7671

So this PR will make the following behavior:
If Event < Today > Event Then by default show Today
If Event < Today Then show max date of Event
If Today > Event Then show min date of Event

That new behavior is documented in the calendar working example, it is the last working example.

close #7671

### CODE REVIEW

**Review by TTVXStarWake — APPROVED** [review]
Thanks Pierre

**Comment by LaurentGoderre** [comment]
@shawnthompson can you create a gh-pages for this?

The code looks clean! Too bad we don't have unit test

**Comment by duboisp** [comment]
@LaurentGoderre 

See here

http://universallabs.org/wet/labs/alt-pr7671/unmin/demos/cal-events/cal-events-en.html
http://universallabs.org/wet/labs/alt-pr7671/unmin/demos/cal-events/cal-events-fr.html

And unit testing: http://universallabs.org/wet/labs/alt-pr7671/unmin/test/test.html

**Comment by duboisp** [comment]
@LaurentGoderre I would submit a new PR with those unit testing may be this week or next week.

**Comment by LaurentGoderre** [comment]
@duboisp these unit test don't apply to the calendar of events though

**Comment by duboisp** [comment]
I know, sorry for the confusion. I will create new test for it

**Comment by LaurentGoderre** [comment]
What I am concerned are the cases not covered here, what happens if there is only event in the current month? or if there is devent in the current month and future or current month and past

**Comment by duboisp** [comment]
I see, but it should be ok. as if event are in the current month only, then minDate and maxDate should be set to be the current month too. So the current month will be show.

I would write specific unit test for those. Although I just made some test locally and it work as expected for those scenario.

**Comment by LaurentGoderre** [comment]
I think this is good to go

**Comment by MaximMartel** [comment]
Thanks Laurent and Pierre !

**Pull request merged**
