### PR TITLE
CSS: Updated styling of fieldset and legend elements.

### PR DESCRIPTION
**Pull request by thomasgohard**
For #6771.

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Is it ready to merge?

**Comment by thomasgohard** [comment]
I'm going to make a couple more changes. Will update this PR shortly.

**Comment by thomasgohard** [comment]
@LaurentGoderre this is ready to merge.

**Comment by hsrudnicki** [comment]
Can this issue be closed as well?

**Pull request merged**
