### PR TITLE
Details/summary: Fixed border shifting CSS issue when expanding/collapsing.

### PR DESCRIPTION
**Pull request by EricDunsworth**
CC @thomasgohard

### CODE REVIEW

**Comment by EricDunsworth** [comment]
Just wondering - is there anything holding back this PR from getting merged in? I'm kind of surprised it wasn't included in v4.0.17.

**Comment by EricDunsworth** [comment]
Btw once #6989 gets merged in, I'll modify this PR if its changes conflict in any way.

**Comment by andre-gh** [comment]
This pull request is lacking a lot of context which is likely why it did not get noticed as much.  I totally understand what happened, at the time whoever you were talking to knew exactly what this was, happens all the tine, but context helps for everyone else looking at pull requests and gets your stuff merged faster.

**Comment by andre-gh** [comment]
I am looking at some details/tabs stuff tomorrow, will attempt to get it merged in then.

**Comment by EricDunsworth** [comment]
@andre-gh Thanks :)!

**Pull request merged**
