### PR TITLE
Fix additional issue (data table and geomap) related to the recent jQuery fix

### PR DESCRIPTION
**Pull request by duboisp**
Fix additional issue related to the recent jQuery fix

* DataTable - Fix loading tabular data via JSON
* Geomap - Fix the data table creation/update

### CODE REVIEW

**Review by Ricokola — APPROVED** [review]
Tested locally and no issue have been identified.

**Comment by duboisp** [comment]
Tested every working example and found no issue.

**Comment by nfrenette** [comment]
Hi,
Is it possible this fix is causing an issue with Lightbox Ajax?

The Ajax gallery on this page is not working:
https://wet-boew.github.io/v4.0-ci/demos/lightbox/lightbox-en.html#examples2

Thanks
@duboisp
@Ricokola

**Comment by duboisp** [comment]
Thanks @nfrenette for reporting the issue. We are working on a fix.

**Pull request merged**
