### PR TITLE
Session-Timeout: Use current time to check if session is expired

### PR DESCRIPTION
**Pull request by radmorecameron**
_(Pick the language of your choice to fill out the following information. / Choisissez la langue de votre choix pour remplir l'information ci-dessous.)_

## What does this pull request (PR) do? / Que fait cette demande « pull » (PR)?

This PR uses the current date and time to check if a session is expired as timeout and intervals can be throttled when in the background.

## Additional information (optional) / Information additionnelle (optionel)

**General checklist / Liste de contrôle générale**
Make your own list for the purpose of your Pull request. /// Faites votre propre liste en fonction des besoins de votre demande « pull ».

- [x] Build and test PR's code /// Rouler le script de compilation et tester le code de la PR

**Related issues / Requêtes associées**
#8045

### CODE REVIEW

**Comment by duboisp** [comment]
Are going to be review by PP this week. We may propose some change request because the CI script is failing. 

Note: Some additional change/adjustment might be required for the corresponding test file here: https://github.com/wet-boew/wet-boew/blob/master/src/plugins/session-timeout/test.js

**Comment by duboisp** [comment]
@polmih poke

**Review by polmih — CHANGES_REQUESTED** [review]
These proposed changes should make the plugin's timing mechanisms compatible with the test expectations, and the test suite should pass without errors and still using the current time in order 
 to check if the session is expired

**Review by polmih — APPROVED** [review]
code review done, tested locally

**Pull request merged**
