### PR TITLE
Fixed tasks not loading when installed in a theme

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by duboisp** [comment]
Is this would fix GCWeb build?

**Review by nschonni — APPROVED** [review]
Didn't run it, but reading the doc it makes sense https://github.com/sindresorhus/load-grunt-tasks#requireresolution
This would allow calling this grunt file without having to restore the node modules into the wet-boew dependency if I'm understanding it

**Comment by LaurentGoderre** [comment]
@duboisp this wont fix the build by itself but is required in order to fix it.

**Comment by LaurentGoderre** [comment]
@nschonni what this does is that if wet is installed via npm, it's dependencies will be in the parent project where grunt can't see them. This allows grunt to traverse up to the parent to find the tasks.

**Comment by LaurentGoderre** [comment]
@duboisp can I merge?

**Pull request merged**
