### PR TITLE
Menu: Explicitly trigger the initialization of the details/summary polyfill

### LINKED ISSUE #7335: Secondary menu and footer mobile expand/collpase polyfill no longer initiated
The expand collapse for the secondary menu and the footer no longer work because they don't appear to be initialized anymore.

### PR DESCRIPTION
**Pull request by LaurentGoderre**
Fixes #7335

### CODE REVIEW

**Comment by andre-gh** [comment]
Thanks, was about to do PR the same thing, merging after it passes

**Comment by LaurentGoderre** [comment]
Usually, when I report a problem, I fix it ;)

**Comment by andre-gh** [comment]
I am approaching my last days with WET so I am much less busy

**Comment by LaurentGoderre** [comment]
Really? Leaving SC?

**Comment by andre-gh** [comment]
The private sector came calling

**Comment by LaurentGoderre** [comment]
Ahh! best of luck!

**Pull request merged**
