### PR TITLE
[DO NOT MERGE] Build: Increased grunt-sass version to 0.18.1.

### LINKED ISSUE #6629: Building WET issue with script\setup
github

Tried using Eric's setup guide and we ran into a whole bunch of issues. It asked for Python to be installed which we did the latest version. We then tried 2.5.9 and 2.5.7 and now we don't seem to get that error anymore.

We tried different version of NPM like @next, @2.5.0 and @2.5.7 and all of them still generate the same error. We could force grunt to compile and would get everything except the CSS files.

Eric even tried copying the files that work on his machine directly onto mine and still doesn't work.

Any ideas? @EricDunsworth  may add additional details.

### PR DESCRIPTION
**Pull request by EricDunsworth**
Fixes #6629.

### CODE REVIEW

**Comment by EricDunsworth** [comment]
Btw I think the build is currently failing on this PR because grunt-jscs was recently upgraded to 1.60. It's complaining about a bunch of JavaScript comments not being preceded by blank lines. None of that stuff has anything to do with this PR.

**Comment by LaurentGoderre** [comment]
Yeah, I will have to fix this and you will need to rebase over it

**Comment by EricDunsworth** [comment]
@LaurentGoderre Do you need a hand fixing that JSCS issue? I could try adding in those blank lines to make it stop freaking out.

**Comment by LaurentGoderre** [comment]
I just did. You only need to rebase.

**Comment by EricDunsworth** [comment]
Ok, done :).

**Comment by EricDunsworth** [comment]
Gonna close this due to the related issues/workaround discussed in #6647.

**Pull request closed without merging**
