### PR TITLE
Build: Append the commit ID to the Travis commit messages

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@nschonni can you please review this?

**Review by nschonni — APPROVED** [review]
LGTM, but i think the "maintenance" word can be removed, although I know it was there before

**Comment by LaurentGoderre** [comment]
Interesting idea! If we are to do this, might as well be specific and say which release it is.

**Comment by LaurentGoderre** [comment]
oh, we're already doing this

**Comment by LaurentGoderre** [comment]
OK, done!

**Pull request merged**
